### ISSUE TITLE
panic when minimizing window since 0.19

### ISSUE THREAD

**Issue by jice-nospam** [emilk/egui#1960]
**Describe the bug**
Since I upgraded to 0.19, the application crashes when I minimize the window.

```thread 'main' panicked at 'Got a texture image of size 0x0. A texture must at least be one texel wide.', ~\.cargo\registry\src\github.com-1ecc6299db9ec823\egui_glow-0.19.0\src\painter.rs:547:9
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\std\src\panicking.rs:584
   1: core::panicking::panic_fmt
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\core\src\panicking.rs:142
   2: egui_glow::painter::Painter::set_texture
   3: egui_glow::painter::Painter::set_texture
   4: egui_glow::painter::Painter::paint_and_update_textures
   5: <eframe::native::run::glow_integration::GlowWinitApp as eframe::native::run::WinitApp>::paint
   6: winit::platform_impl::platform::event_loop::EventLoop<T>::run_return::{{closure}}
   7: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
   8: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<T>::register_window
   9: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<T>::move_state_to
  10: winit::platform_impl::platform::event_loop::public_window_callback_inner::{{closure}}
  11: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<T>::catch_unwind
  12: winit::platform_impl::platform::event_loop::public_window_callback```
The crash occurs in Painter.paint_and_update_textures because it receives an empty texture in the textures_delta parameter

**To Reproduce**
Steps to reproduce the behavior:
1. Start the program with `cargo run --release`
2. Once the window opens, click on it in the task bar to minimize it, or click on the minimize icon in the window title bar
3. => crash

**Desktop (please complete the following information):**
 - OS: Windows 10 64 bits
 - Browser N/A
 - Version N/A

**Additional context**
The application is using three_d and egui_glow : https://github.com/jice-nospam/wgen
I don't reproduce the issue with the three_d or glow examples on master. But on version 0.19.0, the three_d example doesn't start :

```cargo run -p custom_3d_three-d
warning: output filename collision.
The bin target `custom_3d_three-d` in package `custom_3d_three-d v0.1.0 (C:\data\perso\egui\examples\custom_3d_three-d)` has the same output filename as the lib target `custom_3d_three-d` in package `custom_3d_three-d v0.1.0 (C:\data\perso\egui\examples\custom_3d_three-d)`.
Colliding filename is: C:\data\perso\egui\target\debug\deps\custom_3d_three_d.pdb
The targets should have unique names.
Consider changing their names to be unique or compiling them separately.
This may become a hard error in the future; see <https://github.com/rust-lang/cargo/issues/6313>.
warning: output filename collision.
The bin target `custom_3d_three-d` in package `custom_3d_three-d v0.1.0 (C:\data\perso\egui\examples\custom_3d_three-d)` has the same output filename as the lib target `custom_3d_three-d` in package `custom_3d_three-d v0.1.0 (C:\data\perso\egui\examples\custom_3d_three-d)`.
Colliding filename is: C:\data\perso\egui\target\debug\custom_3d_three_d.pdb
The targets should have unique names.
Consider changing their names to be unique or compiling them separately.
This may become a hard error in the future; see <https://github.com/rust-lang/cargo/issues/6313>.
    Finished dev [unoptimized + debuginfo] target(s) in 0.38s
     Running `target\debug\custom_3d_three-d.exe`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NoAvailablePixelFormat', crates\eframe\src\native\run.rs:45:14
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\std\src\panicking.rs:584
   1: core::panicking::panic_fmt
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\core\src\panicking.rs:143
   2: core::result::unwrap_failed
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\/library\core\src\result.rs:1785
   3: enum$<core::result::Result<glutin::windowed::ContextWrapper<enum$<glutin::context::NotCurrent>,winit::window::Window>,enum$<glutin::CreationError> > >::unwrap<glutin::windowed::ContextWrapper<enum$<glutin::context::NotCurrent>,winit::window::Window>,enum$
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\core\src\result.rs:1078
   4: eframe::native::run::create_display
             at .\crates\eframe\src\native\run.rs:37
   5: eframe::native::run::glow_integration::GlowWinitApp::new
             at .\crates\eframe\src\native\run.rs:254
   6: eframe::native::run::glow_integration::run_glow::closure$0
             at .\crates\eframe\src\native\run.rs:458
   7: eframe::native::run::with_event_loop::closure$0<eframe::native::run::glow_integration::run_glow::closure_env$0>
             at .\crates\eframe\src\native\run.rs:84
   8: std::thread::local::LocalKey<core::cell::RefCell<winit::event_loop::EventLoop<eframe::native::run::RequestRepaintEvent> > >::try_with<core::cell::RefCell<winit::event_loop::EventLoop<eframe::native::run::RequestRepaintEvent> >,eframe::native::run::with_ev
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\std\src\thread\local.rs:442
   9: std::thread::local::LocalKey<core::cell::RefCell<winit::event_loop::EventLoop<eframe::native::run::RequestRepaintEvent> > >::with<core::cell::RefCell<winit::event_loop::EventLoop<eframe::native::run::RequestRepaintEvent> >,eframe::native::run::with_event_
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\std\src\thread\local.rs:418
  10: eframe::native::run::with_event_loop<eframe::native::run::glow_integration::run_glow::closure_env$0>
             at .\crates\eframe\src\native\run.rs:83
  11: eframe::native::run::glow_integration::run_glow
             at .\crates\eframe\src\native\run.rs:456
  12: eframe::run_native
             at .\crates\eframe\src\lib.rs:172
  13: custom_3d_three_d::main
             at .\examples\custom_3d_three-d\src\main.rs:15
  14: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e\library\core\src\ops\function.rs:227

**Comment by emilk** [comment]
Sounds like you are creating a texture/image with size 0x0. You shouldn't do that :)

**Comment by emilk** [comment]
Actually, I don't know why that assert is even there. `OpenGL` seems fine with zero-sized textures. I'll just remove it.
