### ISSUE TITLE
running egui_glow  example 

### ISSUE THREAD

**Issue by moohaad** [emilk/egui#2457]
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { raw_code: Some(12291), raw_os_message: None, kind: OutOfMemory }', src/main.rs:77:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by moohaad** [comment]
updated glutin
problem solved

**Comment by MaxBondABE** [comment]
I also encountered this issue on Fedora.

```
thread 'main' panicked at 'failed to create glutin window surface: Error { raw_code: Some(12291), raw_os_message: None, kind: OutOfMemory }',  /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/eframe-0.20.1/src/native/run.rs:409:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by coderedart** [comment]
can you try using https://github.com/coderedart/egui/ repo with `glutin_winit` branch, and see if you still get this crash?

**Comment by MaxBondABE** [comment]
Apologies, I currently don't have access to this computer, I will need to get back to you in approximately two weeks when I have returned from travel.

**Comment by T0rv** [comment]
> can you try using https://github.com/coderedart/egui/ repo with `glutin_winit` branch, and see if you still get this crash?

I had the same error as the topic starter. On `emilk:master`(and stable 20.1 also)
`
2023-02-03T10:15:44.966890Z  INFO winit::platform_impl::platform::x11::window: Guessed window scale factor: 1    
Error: Glutin(Error { raw_code: Some(12291), raw_os_message: None, kind: OutOfMemory })
`
On `coderedart:glutin_winit`
`
2023-02-03T10:17:45.571212Z  INFO winit::platform_impl::platform::x11::window: Guessed window scale factor: 1    
2023-02-03T10:17:45.631782Z  INFO egui_glow::painter: 
opengl version: 4.5 (Core Profile) Mesa 19.2.8
opengl renderer: Mesa DRI Intel(R) UHD Graphics 630 (Coffeelake 3x8 GT2) 
opengl vendor: Intel Open Source Technology Center
`

Looks ok for me at this moment.
Also I noticed the following when clicking on the window cross:
`
thread 'main' panicked at 'Failed to destroy input context: XError { description: "GLXBadWindow", error_code: 170, request_code: 152, minor_code: 32 }', /home/<my_name>/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.5/src/platform_impl/linux/x11/event_processor.rs:523:22
`
<details>
  <summary>stacktrace</summary>

  ```
stack backtrace:
   0:     0x55fb47df9e90 - std::backtrace_rs::backtrace::libunwind::trace::h1d00f3fcf4cb5ac4
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55fb47df9e90 - std::backtrace_rs::backtrace::trace_unsynchronized::h920a6ff332484ee2
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55fb47df9e90 - std::sys_common::backtrace::_print_fmt::hd7323920c925af6d
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x55fb47df9e90 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3155a8c966b4beb5
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55fb47e2003e - core::fmt::write::h062c617411b691df
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/fmt/mod.rs:1209:17
   5:     0x55fb47df4af5 - std::io::Write::write_fmt::hb61fdf1275c61e1c
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/io/mod.rs:1682:15
   6:     0x55fb47df9c55 - std::sys_common::backtrace::_print::hd1b4d9664ab500e0
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x55fb47df9c55 - std::sys_common::backtrace::print::hca896ae22beb06cb
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x55fb47dfb50f - std::panicking::default_hook::{{closure}}::h0b5eeed5cf36ab5f
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:267:22
   9:     0x55fb47dfb24a - std::panicking::default_hook::h8932b573145a321b
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:286:9
  10:     0x55fb47dfbc08 - std::panicking::rust_panic_with_hook::h4b1447a24e3e94f8
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:688:13
  11:     0x55fb47dfb9a7 - std::panicking::begin_panic_handler::{{closure}}::h8701da9995a3820c
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:579:13
  12:     0x55fb47dfa33c - std::sys_common::backtrace::__rust_end_short_backtrace::hb696c5ed02a01598
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/sys_common/backtrace.rs:137:18
  13:     0x55fb47dfb6c2 - rust_begin_unwind
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:575:5
  14:     0x55fb47a8cdc3 - core::panicking::panic_fmt::h8aa706a976963c88
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/panicking.rs:65:14
  15:     0x55fb47a8d083 - core::result::unwrap_failed::h065c02f906ca4578
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/result.rs:1791:5
  16:     0x55fb47b50636 - core::result::Result<T,E>::expect::ha9979f39dbb19a66
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/result.rs:1070:23
  17:     0x55fb47b50636 - winit::platform_impl::platform::x11::event_processor::EventProcessor<T>::process_event::h0d8a566fd755413d
                               at /home/<my_name>/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.5/src/platform_impl/linux/x11/event_processor.rs:520:17
  18:     0x55fb47b38001 - winit::platform_impl::platform::x11::EventLoop<T>::drain_events::h04baf0dacfe55672
                               at /home/<my_name>/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.5/src/platform_impl/linux/x11/mod.rs:517:13
  19:     0x55fb47b38001 - winit::platform_impl::platform::x11::EventLoop<T>::run_return::single_iteration::he1be3963e88d28f2
                               at /home/<my_name>/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.5/src/platform_impl/linux/x11/mod.rs:348:13
  20:     0x55fb47b3850d - winit::platform_impl::platform::x11::EventLoop<T>::run_return::h9475727a689b9d57
                               at /home/<my_name>/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.5/src/platform_impl/linux/x11/mod.rs:448:31
  21:     0x55fb47b2fa9d - winit::platform_impl::platform::EventLoop<T>::run_return::h13e9bc8b6c706eb5
                               at /home/<my_name>/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.5/src/platform_impl/linux/mod.rs:748:56
  22:     0x55fb47b2fa9d - <winit::event_loop::EventLoop<T> as winit::platform::run_return::EventLoopExtRunReturn>::run_return::h4301b3180e45d3c8
                               at /home/<my_name>/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.5/src/platform/run_return.rs:62:9
  23:     0x55fb47b2fa9d - eframe::native::run::run_and_return::hf652f771c85d3a78
                               at /home/<my_name>/.cargo/git/checkouts/egui-af0f7a95a2bef45b/c821bb8/crates/eframe/src/native/run.rs:209:5
  24:     0x55fb47af38fc - eframe::native::run::glow_integration::run_glow::{{closure}}::hba72420c7ab673e4
                               at /home/<my_name>/.cargo/git/checkouts/egui-af0f7a95a2bef45b/c821bb8/crates/eframe/src/native/run.rs:1005:17
  25:     0x55fb47af38fc - eframe::native::run::with_event_loop::{{closure}}::h35ea1925245cccd5
                               at /home/<my_name>/.cargo/git/checkouts/egui-af0f7a95a2bef45b/c821bb8/crates/eframe/src/native/run.rs:99:9
  26:     0x55fb47af38fc - std::thread::local::LocalKey<T>::try_with::hf68b0c56cd5f9b6d
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/thread/local.rs:446:16
  27:     0x55fb47af38fc - std::thread::local::LocalKey<T>::with::h70e8aa9799547282
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/thread/local.rs:422:9
  28:     0x55fb47aef78b - eframe::native::run::with_event_loop::h0957b7744e9becfe
                               at /home/<my_name>/.cargo/git/checkouts/egui-af0f7a95a2bef45b/c821bb8/crates/eframe/src/native/run.rs:92:5
  29:     0x55fb47aef78b - eframe::native::run::glow_integration::run_glow::hb8ee22b9a1cb048a
                               at /home/<my_name>/.cargo/git/checkouts/egui-af0f7a95a2bef45b/c821bb8/crates/eframe/src/native/run.rs:998:13
  30:     0x55fb47b220b7 - eframe::run_native::hd092c4ae4951a92a
                               at /home/<my_name>/.cargo/git/checkouts/egui-af0f7a95a2bef45b/c821bb8/crates/eframe/src/lib.rs:199:13
  31:     0x55fb47ac057e - untitled1::main::hc34b400e1358ce2c
                               at /home/<my_name>/CLionProjects/untitled1/src/main.rs:12:5
  32:     0x55fb47a92c22 - core::ops::function::FnOnce::call_once::hd61e77e4df3b4029
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/ops/function.rs:251:5
  33:     0x55fb47aa73a5 - std::sys_common::backtrace::__rust_begin_short_backtrace::h33e11d30b1da902d
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/sys_common/backtrace.rs:121:18
  34:     0x55fb47ac24a9 - std::rt::lang_start::{{closure}}::h6a00a797727ab17c
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/rt.rs:166:18
  35:     0x55fb47df011b - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h8cbb48ae40ddb046
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/ops/function.rs:286:13
  36:     0x55fb47df011b - std::panicking::try::do_call::h92db802eb38b49b7
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:483:40
  37:     0x55fb47df011b - std::panicking::try::ha8949d2082cf3644
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:447:19
  38:     0x55fb47df011b - std::panic::catch_unwind::h5e34c1f8a5992ed9
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panic.rs:137:14
  39:     0x55fb47df011b - std::rt::lang_start_internal::{{closure}}::hea52a0bb3f8ff16a
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/rt.rs:148:48
  40:     0x55fb47df011b - std::panicking::try::do_call::h5bc358faf3d68a8b
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:483:40
  41:     0x55fb47df011b - std::panicking::try::h675304212928379d
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:447:19
  42:     0x55fb47df011b - std::panic::catch_unwind::h7ce3ad349ed5c844
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panic.rs:137:14
  43:     0x55fb47df011b - std::rt::lang_start_internal::hcd7e45acd25ab5ab
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/rt.rs:148:20
  44:     0x55fb47ac247a - std::rt::lang_start::hcdb4bf08dffc675d
                               at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/rt.rs:165:17
  45:     0x55fb47ac06ee - main
  46:     0x7f2edefb2c87 - __libc_start_main
                               at /build/glibc-uZu3wS/glibc-2.27/csu/../csu/libc-start.c:310
  47:     0x55fb47a8d21a - _start
  48:                0x0 - <unknown>

Process finished with exit code 101

  ```
</details>

I dunno but looks weird or is that how it is supposed to work?

**Comment by coderedart** [comment]
@T0rv can you provide the logs output too. 
`RUST_LOG=debug cargo run -p hello_world`

that close button crash could be due to dropping the winit window before glutin surface of that window.  
logs will help me pinpoint it better.

The PR https://github.com/emilk/egui/pull/2526 should atleast fix your eframe master branch crash at startup. I will ping egui developer again to see if we can hurry the merge.

**Comment by T0rv** [comment]
@coderedart 
Seems like your recent commit fixed this "cross issue".
Just in case logs for both versions:
<details>
  <summary>RUST_LOG=debug on rev = "d2f6a90" current</summary>
```
2023-02-03T12:12:20.586020Z DEBUG eframe: Using the glow renderer
2023-02-03T12:12:20.596767Z DEBUG eframe::native::run: Entering the winit event loop (run_return)…
2023-02-03T12:12:20.596893Z DEBUG eframe::native::run::glow_integration: trying to create glutin Display with config: ConfigTemplateBuilder { template: ConfigTemplate { color_buffer_type: Rgb { r_size: 8, g_size: 8, b_size: 8 }, alpha_size: 8, depth_size: 0, stencil_size: 0, num_samples: None, min_swap_interval: None, max_swap_interval: None, config_surface_types: WINDOW, api: None, transparency: false, single_buffering: false, stereoscopy: None, float_pixels: false, max_pbuffer_width: None, hardware_accelerated: None, max_pbuffer_height: None, native_window: None } }
2023-02-03T12:12:20.607477Z DEBUG eframe::native::run::glow_integration: using the first config from config picker closure. config: Glx(Config { inner: Config { raw: GlxConfig(0x5566a06ed860), display: GlxDisplay(0x5566a0550170) } })
2023-02-03T12:12:20.613921Z  INFO winit::platform_impl::platform::x11::window: Guessed window scale factor: 1    
2023-02-03T12:12:20.613944Z DEBUG winit::platform_impl::platform::x11::window: Calculated physical dimensions: 320x240    
2023-02-03T12:12:20.616379Z DEBUG winit::platform_impl::platform::x11::ime: failed to create IME context without preedit support.    
2023-02-03T12:12:20.616498Z DEBUG eframe::native::run::glow_integration: successfully created GL Display with version: GLX 1.4 and supported features: CONTEXT_ROBUSTNESS | CONTEXT_NO_ERROR | FLOAT_PIXEL_FORMAT | SWAP_CONTROL | CONTEXT_RELEASE_BEHAVIOR | CREATE_ES_CONTEXT | MULTISAMPLING_PIXEL_FORMATS | SRGB_FRAMEBUFFERS
2023-02-03T12:12:20.616505Z DEBUG eframe::native::run::glow_integration: creating gl context using raw window handle: Some(Xlib(XlibWindowHandle { window: 67108868, visual_id: 0 }))
2023-02-03T12:12:20.617997Z DEBUG eframe::native::run::glow_integration: running on_resume fn.
2023-02-03T12:12:20.618079Z DEBUG eframe::native::run::glow_integration: creating surface with attributes: SurfaceAttributes { srgb: None, single_buffer: false, width: Some(320), height: Some(240), largest_pbuffer: false, raw_window_handle: Some(Xlib(XlibWindowHandle { window: 67108868, visual_id: 0 })), native_pixmap: None, _ty: PhantomData<glutin::surface::WindowSurface> }
2023-02-03T12:12:20.618233Z DEBUG eframe::native::run::glow_integration: surface created successfully: Glx(Surface { display: GlxDisplay(0x5566a0550170), config: GlxConfig(0x5566a06ed860), raw: 67108869, type: Window }).making context current
2023-02-03T12:12:20.620467Z DEBUG eframe::native::run::glow_integration: made context current. setting swap interval for surface
2023-02-03T12:12:20.621610Z  INFO egui_glow::painter: 
opengl version: 4.5 (Core Profile) Mesa 19.2.8
opengl renderer: Mesa DRI Intel(R) UHD Graphics 630 (Coffeelake 3x8 GT2) 
opengl vendor: Intel Open Source Technology Center
2023-02-03T12:12:20.621622Z DEBUG egui_glow::shader_version: Shader version: Gl140 ("4.50").
2023-02-03T12:12:20.621626Z DEBUG egui_glow::painter: Shader header: "#version 140\n".
2023-02-03T12:12:20.621631Z DEBUG egui_glow::painter: SRGB texture Support: true
2023-02-03T12:12:20.621763Z DEBUG egui_glow::vao: GL version: "4.5 (Core Profile) Mesa 19.2.8".
2023-02-03T12:12:20.622093Z DEBUG egui_winit::clipboard: Initializing arboard clipboard…
2023-02-03T12:12:20.622390Z DEBUG egui_winit::clipboard: Cannot initialize smithay clipboard without a display handle
2023-02-03T12:12:31.192592Z DEBUG eframe::native::epi_integration: Received WindowEvent::CloseRequested
2023-02-03T12:12:31.192606Z DEBUG eframe::native::epi_integration: App::on_close_event returned true
2023-02-03T12:12:31.192610Z DEBUG eframe::native::run: Asking to exit event loop…
2023-02-03T12:12:31.192625Z DEBUG eframe::native::run: Received Event::LoopDestroyed - saving app state…
2023-02-03T12:12:31.193498Z DEBUG eframe::native::run: eframe window closed
```
</details>

<details>
  <summary>RUST_LOG=debug on rev = "c821bb8717d9c014a973c498ef753a8429fb85ac" previous</summary>
```
2023-02-03T12:11:18.392850Z DEBUG eframe: Using the glow renderer
2023-02-03T12:11:18.396940Z DEBUG eframe::native::run: Entering the winit event loop (run_return)…
2023-02-03T12:11:18.397095Z DEBUG eframe::native::run::glow_integration: trying to create glutin Display with config: ConfigTemplateBuilder { template: ConfigTemplate { color_buffer_type: Rgb { r_size: 8, g_size: 8, b_size: 8 }, alpha_size: 8, depth_size: 0, stencil_size: 0, num_samples: None, min_swap_interval: None, max_swap_interval: None, config_surface_types: WINDOW, api: None, transparency: false, single_buffering: false, stereoscopy: None, float_pixels: false, max_pbuffer_width: None, hardware_accelerated: None, max_pbuffer_height: None, native_window: None } }
2023-02-03T12:11:18.418034Z DEBUG eframe::native::run::glow_integration: using the first config from config picker closure. config: Glx(Config { inner: Config { raw: GlxConfig(0x555965d2c860), display: GlxDisplay(0x555965b8f170) } })
2023-02-03T12:11:18.418681Z  INFO winit::platform_impl::platform::x11::window: Guessed window scale factor: 1    
2023-02-03T12:11:18.418690Z DEBUG winit::platform_impl::platform::x11::window: Calculated physical dimensions: 320x240    
2023-02-03T12:11:18.420159Z DEBUG winit::platform_impl::platform::x11::ime: failed to create IME context without preedit support.    
2023-02-03T12:11:18.420234Z DEBUG eframe::native::run::glow_integration: successfully created GL Display with version: GLX 1.4 and supported features: CONTEXT_ROBUSTNESS | CONTEXT_NO_ERROR | FLOAT_PIXEL_FORMAT | SWAP_CONTROL | CONTEXT_RELEASE_BEHAVIOR | CREATE_ES_CONTEXT | MULTISAMPLING_PIXEL_FORMATS | SRGB_FRAMEBUFFERS
2023-02-03T12:11:18.420242Z DEBUG eframe::native::run::glow_integration: creating gl context using raw window handle: Some(Xlib(XlibWindowHandle { window: 67108868, visual_id: 0 }))
2023-02-03T12:11:18.421704Z DEBUG eframe::native::run::glow_integration: running on_resume fn.
2023-02-03T12:11:18.421821Z DEBUG eframe::native::run::glow_integration: creating surface with attributes: SurfaceAttributes { srgb: None, single_buffer: false, width: Some(320), height: Some(240), largest_pbuffer: false, raw_window_handle: Some(Xlib(XlibWindowHandle { window: 67108868, visual_id: 0 })), native_pixmap: None, _ty: PhantomData<glutin::surface::WindowSurface> }
2023-02-03T12:11:18.422754Z DEBUG eframe::native::run::glow_integration: surface created successfully: Glx(Surface { display: GlxDisplay(0x555965b8f170), config: GlxConfig(0x555965d2c860), raw: 67108869, type: Window }).making context current
2023-02-03T12:11:18.425547Z DEBUG eframe::native::run::glow_integration: made context current. setting swap interval for surface
2023-02-03T12:11:18.426563Z  INFO egui_glow::painter: 
opengl version: 4.5 (Core Profile) Mesa 19.2.8
opengl renderer: Mesa DRI Intel(R) UHD Graphics 630 (Coffeelake 3x8 GT2) 
opengl vendor: Intel Open Source Technology Center
2023-02-03T12:11:18.426578Z DEBUG egui_glow::shader_version: Shader version: Gl140 ("4.50").
2023-02-03T12:11:18.426582Z DEBUG egui_glow::painter: Shader header: "#version 140\n".
2023-02-03T12:11:18.426588Z DEBUG egui_glow::painter: SRGB texture Support: true
2023-02-03T12:11:18.426737Z DEBUG egui_glow::vao: GL version: "4.5 (Core Profile) Mesa 19.2.8".
2023-02-03T12:11:18.426968Z DEBUG egui_winit::clipboard: Initializing arboard clipboard…
2023-02-03T12:11:18.427278Z DEBUG egui_winit::clipboard: Cannot initialize smithay clipboard without a display handle
2023-02-03T12:11:30.244176Z DEBUG eframe::native::epi_integration: Received WindowEvent::CloseRequested
2023-02-03T12:11:30.244221Z DEBUG eframe::native::epi_integration: App::on_close_event returned true
2023-02-03T12:11:30.244238Z DEBUG eframe::native::run: Asking to exit event loop…
2023-02-03T12:11:30.244315Z DEBUG eframe::native::run: Received Event::LoopDestroyed - saving app state…
2023-02-03T12:11:30.248921Z DEBUG eframe::native::run: eframe window closed
thread 'main' panicked at 'Failed to destroy input context: XError { description: "GLXBadWindow", error_code: 170, request_code: 152, minor_code: 32 }', /home/platonov/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.5/src/platform_impl/linux/x11/event_processor.rs:523:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```
</details>

**Comment by veto64** [comment]
Cannot run any egui app on one particular debian11 laptop.
Compiles ok, but cannot run.

Getting this when I execute it:

thread 'main' panicked at 'failed to create glutin window surface: Error { raw_code: Some(12291), raw_os_message: None, kind: OutOfMemory }', /home/veto/.cargo/registry/src/github.com-1ecc6299db9ec823/eframe-0.20.1/src/native/run.rs:409:18
stack backtrace:


my system:
inxi -G -S -x
System:    Host: hellas Kernel: 5.10.0-20-amd64 x86_64 bits: 64 compiler: gcc v: 10.2.1 Desktop: Xfce 4.16.0 
           Distro: Debian GNU/Linux 11 (bullseye) 
Graphics:  Device-1: Intel 4th Gen Core Processor Integrated Graphics vendor: Micro-Star MSI driver: i915 v: kernel 
           bus ID: 00:02.0 
           Device-2: NVIDIA GK104M [GeForce GTX 860M] vendor: Micro-Star MSI driver: nouveau v: kernel bus ID: 01:00.0 
           Display: x11 server: X.Org 1.20.11 driver: loaded: modesetting unloaded: fbdev,vesa resolution: 1920x1080~60Hz 
           OpenGL: renderer: Mesa DRI Intel HD Graphics 4600 (HSW GT2) v: 4.5 Mesa 20.3.5 direct render: Yes

**Comment by jossriLDR** [comment]
Same issue here

```
thread 'main' panicked at 'failed to create glutin window surface: Error { raw_code: Some(12291), raw_os_message: None, kind: OutOfMemory }', ~/.cargo/registry/src/github.com-1ecc6299db9ec823/eframe-0.20.1/src/native/run.rs:409:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

On my Debian 11 Laptop:
```
System:    Host: ... Kernel: 5.10.0-21-amd64 x86_64 bits: 64 compiler: gcc v: 10.2.1 Console: tty 22
           Distro: Debian GNU/Linux 11 (bullseye)
Graphics:  Device-1: NVIDIA GM107GL [Quadro K620] driver: nouveau v: kernel bus ID: 03:00.0
           Display: server: X.org 1.20.11 driver: loaded: modesetting unloaded: fbdev,vesa tty: 119x50
```

**Comment by coderedart** [comment]
@jossriLDR are you using the latest egui (0.21) ?

post the logs output. and output of `glxinfo` and `eglinfo`. If you are using the latest egui version, the problem could be with nouveau drivers.

**Comment by jossriLDR** [comment]
Yes, updating fixed it for me, thank you. I just updated my post.

**Comment by coderedart** [comment]
@emilk this issue can be closed.

**Comment by emilk** [comment]
❤️ thanks you @coderedart
