### ISSUE TITLE
Zooming out too far in plot panics

### ISSUE THREAD

**Issue by IFcoltransG** [emilk/egui#2630]
If you zoom out very (very) far on a plot, an f64 doesn't have enough precision track scrolling. So after zooming out far enough, scrolling panics on an assertion.

**To Reproduce**
1. Create any plot.
```rs
use eframe::egui;
fn main() {
    eframe::run_native("view", Default::default(), Box::new(|_| Box::new(MyApp)));
}
struct MyApp;

impl eframe::App for MyApp {
    fn update(&mut self, ctx: &egui::Context, _: &mut eframe::Frame) {
        egui::CentralPanel::default().show(ctx, |ui| {
            egui::plot::Plot::new("plot").show(ui, |_| {});
        });
    }
}

```
2. Zoom out for a long way, by holding ctrl and scrolling down on a trackpad.
3. Once you've scrolled very high, click and drag to scroll the plot a small amount.
4. See panic message:
`thread 'main' panicked at 'assertion failed: min <= max', /rustc/.../library/core/src/num/f64.rs:1392:9`

**Expected behavior**
Plot scrolls normally, or refuses to scroll. No panic.

**Details:**
OS: Linux 6.1.1
Version: eframe 0.20.1
I wasn't able to compile the master branch.

**Comment by YgorSouza** [comment]
Here is the relevant part of the stack trace on the egui, tested on 530e9f667c0969b09edb68f7701f20c52a273d3a:

<Details><Summary>Debug</Summary>

```
thread 'main' panicked at 'assertion failed: min <= max', /rustc/897e37553bba8b42751c67658967889d11ecd120
/library/core/src/num/f64.rs:1392:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:48:5
   3: core::f64::<impl f64>::clamp
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/num/f64.rs:1392:9
   4: egui::widgets::plot::PreparedPlot::paint_axis
             at ./crates/egui/src/widgets/plot/mod.rs:1445:27
   5: egui::widgets::plot::PreparedPlot::ui
             at ./crates/egui/src/widgets/plot/mod.rs:1335:17
   6: egui::widgets::plot::Plot::show_dyn
             at ./crates/egui/src/widgets/plot/mod.rs:997:28
   7: egui::widgets::plot::Plot::show
```
</Details>

<Details><Summary>Release</Summary>

```
thread 'main' panicked at 'assertion failed: max > min', crates/egui/src/widgets/plot/mod.rs:1645:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:48:5
   3: egui::widgets::plot::generate_marks
   4: egui::widgets::plot::log_grid_spacer::{{closure}}
   5: egui::widgets::plot::PreparedPlot::ui
   6: egui::widgets::plot::Plot::show_dyn
   7: <egui_demo_lib::demo::plot_demo::PlotDemo as egui_demo_lib::demo::View>::ui
```

</Details>

Also, I added a `dbg!` to one of the lines where it was panicking, and these were the last prints:

```
[crates/egui/src/widgets/plot/mod.rs:1445] bounds.min[1 - axis] = -1.2722932166922171e44
[crates/egui/src/widgets/plot/mod.rs:1445] bounds.max[1 - axis] = 1.8239042690067835e44
[crates/egui/src/widgets/plot/mod.rs:1445] bounds.min[1 - axis] = NaN
[crates/egui/src/widgets/plot/mod.rs:1445] bounds.max[1 - axis] = NaN
```

So it looks like NaN is sneaking through at some point, even though there is a check for it when changing the bounds.

**Comment by emilk** [comment]
I think this is solved now
