### ISSUE TITLE
`clamp_window_to_sane_position` causes panic

### ISSUE THREAD

**Issue by aevyrie** [emilk/egui#2721]
**Describe the bug**

Demo app panics sporadically, hard to reproduce reliably, but seems to get stuck in a broken state, presumably because the window position/size can be in a malformed state.

```
thread 'main' panicked at 'assertion failed: min <= max', /rustc/897e37553bba8b42751c67658967889d11ecd120\library\core\src\num\f32.rs:1394:9
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panicking.rs:584
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\core\src\panicking.rs:142
   2: core::panicking::panic
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\core\src\panicking.rs:48
   3: core::f32::impl$0::clamp
             at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\core\src\num\f32.rs:1394
   4: emath::pos2::Pos2::clamp
             at .\crates\emath\src\pos2.rs:188
   5: egui_winit::window_settings::WindowSettings::clamp_window_to_sane_position<enum2$<eframe::native::run::UserEvent> >
             at .\crates\egui-winit\src\window_settings.rs:132
```

**To Reproduce**
1. Build the egui demo app on windows

**Desktop (please complete the following information):**
 - OS:  Windows 11
 - Version 0.21 - master

**Additional context**

**Comment by aevyrie** [comment]
The assertion is triggering because the RHS of the `clamp` is smaller than the LHS.
