### ISSUE TITLE
`egui_demo_app` panicked

### ISSUE THREAD

**Issue by 3119369616** [emilk/egui#2840]
**Describe the bug**

```
thread 'main' panicked at 'assertion failed: min <= max', /rustc/897e37553bba8b42751c67658967889d11ecd120\library\core\src\num\f32.rs:1394:9
stack backtrace:
   0:     0x7ff713869312 - std::backtrace_rs::backtrace::dbghelp::trace
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
   1:     0x7ff713869312 - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff713869312 - std::sys_common::backtrace::_print_fmt
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\sys_common\backtrace.rs:66
   3:     0x7ff713869312 - std::sys_common::backtrace::_print::impl$0::fmt
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\sys_common\backtrace.rs:45
   4:     0x7ff71388b25b - core::fmt::write
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\core\src\fmt\mod.rs:1202
   5:     0x7ff71386457a - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\io\mod.rs:1679
   6:     0x7ff71386bd44 - std::sys_common::backtrace::_print
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\sys_common\backtrace.rs:48
   7:     0x7ff71386bd44 - std::sys_common::backtrace::print
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\sys_common\backtrace.rs:35
   8:     0x7ff71386bd44 - std::panicking::default_hook::closure$1
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panicking.rs:295
   9:     0x7ff71386b97a - std::panicking::default_hook
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panicking.rs:314
  10:     0x7ff71386c531 - std::panicking::rust_panic_with_hook
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panicking.rs:698
  11:     0x7ff71386c3fa - std::panicking::begin_panic_handler::closure$0
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panicking.rs:586
  12:     0x7ff71386a01f - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\sys_common\backtrace.rs:138
  13:     0x7ff71386c100 - std::panicking::begin_panic_handler
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panicking.rs:584
  14:     0x7ff7138b1b65 - core::panicking::panic_fmt
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\core\src\panicking.rs:142
  15:     0x7ff7138b1a0c - core::panicking::panic
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\core\src\panicking.rs:48
  16:     0x7ff712f307d5 - core::f32::impl$0::clamp
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\core\src\num\f32.rs:1394
  17:     0x7ff712f4dbf0 - emath::pos2::Pos2::clamp
                               at e:\t\egui-0.21.0\crates\emath\src\pos2.rs:187
  18:     0x7ff712f1e5eb - egui_winit::window_settings::WindowSettings::clamp_window_to_sane_position<enum2$<eframe::native::run::UserEvent> >
                               at e:\t\egui-0.21.0\crates\egui-winit\src\window_settings.rs:132
  19:     0x7ff712f0c258 - eframe::native::epi_integration::window_builder<enum2$<eframe::native::run::UserEvent> >
                               at e:\t\egui-0.21.0\crates\eframe\src\native\epi_integration.rs:127
  20:     0x7ff712ebd4c5 - eframe::native::run::glow_integration::GlowWinitApp::create_glutin_windowed_context
                               at e:\t\egui-0.21.0\crates\eframe\src\native\run.rs:632
  21:     0x7ff712ebd986 - eframe::native::run::glow_integration::GlowWinitApp::init_run_state
                               at e:\t\egui-0.21.0\crates\eframe\src\native\run.rs:657
  22:     0x7ff712ebf3dd - eframe::native::run::glow_integration::impl$2::on_event
                               at e:\t\egui-0.21.0\crates\eframe\src\native\run.rs:874
  23:     0x7ff712f02df6 - eframe::native::run::run_and_return::closure$0<eframe::native::run::glow_integration::GlowWinitApp>
                               at e:\t\egui-0.21.0\crates\eframe\src\native\run.rs:152
  24:     0x7ff712ed9e07 - winit::platform_impl::platform::event_loop::impl$3::run_return::closure$0<enum2$<eframe::native::run::UserEvent>,eframe::native::run::run_and_return::closure_env$0<eframe::native::run::glow_integration::GlowWinitApp> >
                               at D:\Rust\Cargo\registry\src\mirrors.ustc.edu.cn-b63e9dae659fc205\winit-0.28.1\src\platform_impl\windows\event_loop.rs:256
  25:     0x7ff712ec1084 - alloc::boxed::impl$45::call_mut<tuple$<enum2$<winit::event::Event<enum2$<eframe::native::run::UserEvent> > >,ref_mut$<enum2$<winit::event_loop::ControlFlow> > >,dyn$<core::ops::function::FnMut<tuple$<enum2$<winit::event::Event<enum2$<eframe::native::run::
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\alloc\src\boxed.rs:1947
  26:     0x7ff712f3d98b - winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure$0<enum2$<eframe::native::run::UserEvent> >
                               at D:\Rust\Cargo\registry\src\mirrors.ustc.edu.cn-b63e9dae659fc205\winit-0.28.1\src\platform_impl\windows\event_loop\runner.rs:250
  27:     0x7ff712f52194 - core::panic::unwind_safe::impl$23::call_once<tuple$<>,winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<enum2$<eframe::native::run::UserEvent> > >
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\core\src\panic\unwind_safe.rs:271
  28:     0x7ff712f46f88 - std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<enum2$<eframe::native::run::UserEvent> > >,tuple$<> >
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\std\src\panicking.rs:492
  29:     0x7ff712f476c3 - std::panicking::try::do_catch<core::panic::unwind_safe::AssertUnwindSafe<std::thread::impl$0::spawn_unchecked_::closure$1::closure_env$0<eframe::native::file_storage::impl$2::flush::closure_env$0,tuple$<> > >,tuple$<> >
  30:     0x7ff712f46aa0 - std::panicking::try<tuple$<>,core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<enum2$<eframe::native::run::UserEvent> > > >
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\std\src\panicking.rs:456
  31:     0x7ff712ef1754 - std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<enum2$<eframe::native::run::UserEvent> > >,tuple$<> >
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\std\src\panic.rs:137
  32:     0x7ff712f3abfd - winit::platform_impl::platform::event_loop::runner::EventLoopRunner<enum2$<eframe::native::run::UserEvent> >::catch_unwind<enum2$<eframe::native::run::UserEvent>,tuple$<>,winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::clos
                               at D:\Rust\Cargo\registry\src\mirrors.ustc.edu.cn-b63e9dae659fc205\winit-0.28.1\src\platform_impl\windows\event_loop\runner.rs:157
  33:     0x7ff712f3d70c - winit::platform_impl::platform::event_loop::runner::EventLoopRunner<enum2$<eframe::native::run::UserEvent> >::call_event_handler<enum2$<eframe::native::run::UserEvent> >
                               at D:\Rust\Cargo\registry\src\mirrors.ustc.edu.cn-b63e9dae659fc205\winit-0.28.1\src\platform_impl\windows\event_loop\runner.rs:242
  34:     0x7ff712f3cb13 - winit::platform_impl::platform::event_loop::runner::EventLoopRunner<enum2$<eframe::native::run::UserEvent> >::call_new_events<enum2$<eframe::native::run::UserEvent> >
                               at D:\Rust\Cargo\registry\src\mirrors.ustc.edu.cn-b63e9dae659fc205\winit-0.28.1\src\platform_impl\windows\event_loop\runner.rs:402
  35:     0x7ff712f3c1e1 - winit::platform_impl::platform::event_loop::runner::EventLoopRunner<enum2$<eframe::native::run::UserEvent> >::move_state_to<enum2$<eframe::native::run::UserEvent> >
                               at D:\Rust\Cargo\registry\src\mirrors.ustc.edu.cn-b63e9dae659fc205\winit-0.28.1\src\platform_impl\windows\event_loop\runner.rs:312
  36:     0x7ff712f3e267 - winit::platform_impl::platform::event_loop::runner::EventLoopRunner<enum2$<eframe::native::run::UserEvent> >::poll<enum2$<eframe::native::run::UserEvent> >
                               at D:\Rust\Cargo\registry\src\mirrors.ustc.edu.cn-b63e9dae659fc205\winit-0.28.1\src\platform_impl\windows\event_loop\runner.rs:206
  37:     0x7ff712ed8e8b - winit::platform_impl::platform::event_loop::EventLoop<enum2$<eframe::native::run::UserEvent> >::run_return<enum2$<eframe::native::run::UserEvent>,eframe::native::run::run_and_return::closure_env$0<eframe::native::run::glow_integration::GlowWinitApp> >
                               at D:\Rust\Cargo\registry\src\mirrors.ustc.edu.cn-b63e9dae659fc205\winit-0.28.1\src\platform_impl\windows\event_loop.rs:265
  38:     0x7ff712f0a2ed - winit::platform::run_return::impl$0::run_return<enum2$<eframe::native::run::UserEvent>,eframe::native::run::run_and_return::closure_env$0<eframe::native::run::glow_integration::GlowWinitApp> >
                               at D:\Rust\Cargo\registry\src\mirrors.ustc.edu.cn-b63e9dae659fc205\winit-0.28.1\src\platform\run_return.rs:51
  39:     0x7ff712f027c0 - eframe::native::run::run_and_return<eframe::native::run::glow_integration::GlowWinitApp>
                               at e:\t\egui-0.21.0\crates\eframe\src\native\run.rs:115
  40:     0x7ff712ed71df - eframe::native::run::glow_integration::run_glow::closure$0
                               at e:\t\egui-0.21.0\crates\eframe\src\native\run.rs:985
  41:     0x7ff712f01732 - eframe::native::run::with_event_loop::closure$0<enum2$<core::result::Result<tuple$<>,enum2$<eframe::Error> > >,eframe::native::run::glow_integration::run_glow::closure_env$0>
                               at e:\t\egui-0.21.0\crates\eframe\src\native\run.rs:99
  42:     0x7ff712efe678 - std::thread::local::LocalKey<core::cell::RefCell<enum2$<core::option::Option<winit::event_loop::EventLoop<enum2$<eframe::native::run::UserEvent> > > > > >::try_with<core::cell::RefCell<enum2$<core::option::Option<winit::event_loop::EventLoop<enum2$<eframe
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\std\src\thread\local.rs:445
  43:     0x7ff712efe0d5 - std::thread::local::LocalKey<core::cell::RefCell<enum2$<core::option::Option<winit::event_loop::EventLoop<enum2$<eframe::native::run::UserEvent> > > > > >::with<core::cell::RefCell<enum2$<core::option::Option<winit::event_loop::EventLoop<enum2$<eframe::na
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\std\src\thread\local.rs:421
  44:     0x7ff712f01420 - eframe::native::run::with_event_loop<enum2$<core::result::Result<tuple$<>,enum2$<eframe::Error> > >,eframe::native::run::glow_integration::run_glow::closure_env$0>
                               at e:\t\egui-0.21.0\crates\eframe\src\native\run.rs:92
  45:     0x7ff712ec006d - eframe::native::run::glow_integration::run_glow
                               at e:\t\egui-0.21.0\crates\eframe\src\native\run.rs:982
  46:     0x7ff712e8b598 - eframe::run_native
                               at e:\t\egui-0.21.0\crates\eframe\src\lib.rs:199
  47:     0x7ff712c81595 - egui_demo_app::main
                               at e:\t\egui-0.21.0\crates\egui_demo_app\src\main.rs:31
  48:     0x7ff712c81883 - core::ops::function::FnOnce::call_once<enum2$<core::result::Result<tuple$<>,enum2$<eframe::Error> > > (*)(),tuple$<> >
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\core\src\ops\function.rs:248
  49:     0x7ff712c82366 - std::sys_common::backtrace::__rust_begin_short_backtrace<enum2$<core::result::Result<tuple$<>,enum2$<eframe::Error> > > (*)(),enum2$<core::result::Result<tuple$<>,enum2$<eframe::Error> > > >
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\std\src\sys_common\backtrace.rs:122
  50:     0x7ff712c8249c - std::rt::lang_start::closure$0<enum2$<core::result::Result<tuple$<>,enum2$<eframe::Error> > > >
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\std\src\rt.rs:166
  51:     0x7ff71385fe4e - core::ops::function::impls::impl$2::call_once
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\core\src\ops\function.rs:283
  52:     0x7ff71385fe4e - std::panicking::try::do_call
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panicking.rs:492
  53:     0x7ff71385fe4e - std::panicking::try
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panicking.rs:456
  54:     0x7ff71385fe4e - std::panic::catch_unwind
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panic.rs:137
  55:     0x7ff71385fe4e - std::rt::lang_start_internal::closure$2
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\rt.rs:148
  56:     0x7ff71385fe4e - std::panicking::try::do_call
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panicking.rs:492
  57:     0x7ff71385fe4e - std::panicking::try
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panicking.rs:456
  58:     0x7ff71385fe4e - std::panic::catch_unwind
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panic.rs:137
  59:     0x7ff71385fe4e - std::rt::lang_start_internal
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\rt.rs:148
  60:     0x7ff712c8246a - std::rt::lang_start<enum2$<core::result::Result<tuple$<>,enum2$<eframe::Error> > > >
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\std\src\rt.rs:165
  61:     0x7ff712c8173c - main
  62:     0x7ff713893c0c - invoke_main
                               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  63:     0x7ff713893c0c - __scrt_common_main_seh
                               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  64:     0x7ffeaf5f7614 - BaseThreadInitThunk
  65:     0x7ffeb03a26a1 - RtlUserThreadStart
```

**To Reproduce**
1. Build `egui_demo_app` in release mode but it crashes.
2. Rebuild it in debug mode and it dumps the information above.

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/38552079/227716638-230dcf89-f1ef-485c-8880-f49c327024ca.png)

**Desktop (please complete the following information):**
 - OS: 64-bit Windows 10
 - Version : VS Build Tools 2022, MSVC 143, Windows 11 SDK 10.0.22621.0

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by YgorSouza** [comment]
This seems to have been fixed by https://github.com/emilk/egui/pull/2722. The line number `crates\egui-winit\src\window_settings.rs:132` suggests that this is a build from before the fix. Can you try the latest commit on master?
