### ISSUE TITLE
Demo app panics if you click on Organize windows

### ISSUE THREAD

**Issue by YgorSouza** [emilk/egui#3566]
**Describe the bug**

The demo app panics if you click on the "Organize windows" button in the bottom right corner. Both on Desktop and Web.

**Desktop (please complete the following information):**
 - OS:  Fedora 38
 - Browser  Firefox
 - Version 119.0.1

**Additional context**

Bug introduced by #3172 (confirmed via bisect).

Backtrace:

<Details>

```
thread 'main' panicked at 'Memory broken: no area for the current viewport', crates/egui/src/memory.rs:589:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
   2: core::panicking::panic_display
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:150:5
   3: core::panicking::panic_str
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:134:5
   4: core::option::expect_failed
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/option.rs:2025:5
   5: core::option::Option<T>::expect
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/option.rs:913:21
   6: egui::memory::Memory::areas
             at ./crates/egui/src/memory.rs:587:9
   7: egui::memory::Memory::layer_id_at
             at ./crates/egui/src/memory.rs:599:9
   8: egui::context::Context::layer_id_at::{{closure}}
             at ./crates/egui/src/context.rs:1833:13
   9: egui::context::Context::memory::{{closure}}
             at ./crates/egui/src/context.rs:587:30
  10: egui::context::Context::read
             at ./crates/egui/src/context.rs:480:9
  11: egui::context::Context::memory
             at ./crates/egui/src/context.rs:587:9
  12: egui::context::Context::layer_id_at
             at ./crates/egui/src/context.rs:1832:9
  13: egui::context::Context::rect_contains_pointer
             at ./crates/egui/src/context.rs:1848:47
  14: egui::context::Context::interact
             at ./crates/egui/src/context.rs:798:27
  15: egui::ui::Ui::interact
             at ./crates/egui/src/ui.rs:628:9
  16: egui::ui::Ui::with_layout_dyn
             at ./crates/egui/src/ui.rs:2013:35
  17: egui::ui::Ui::with_layout
             at ./crates/egui/src/ui.rs:1999:9
  18: egui_demo_lib::demo::demo_app_windows::DemoWindows::demo_list_ui::{{closure}}
             at ./crates/egui_demo_lib/src/demo/demo_app_windows.rs:286:13
  19: egui::containers::scroll_area::ScrollArea::show::{{closure}}
             at ./crates/egui/src/containers/scroll_area.rs:608:61
  20: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5
  21: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1973:9
  22: egui::containers::scroll_area::ScrollArea::show_viewport_dyn
             at ./crates/egui/src/containers/scroll_area.rs:680:21
  23: egui::containers::scroll_area::ScrollArea::show
             at ./crates/egui/src/containers/scroll_area.rs:608:9
  24: egui_demo_lib::demo::demo_app_windows::DemoWindows::demo_list_ui
             at ./crates/egui_demo_lib/src/demo/demo_app_windows.rs:285:9
  25: egui_demo_lib::demo::demo_app_windows::DemoWindows::desktop_ui::{{closure}}
             at ./crates/egui_demo_lib/src/demo/demo_app_windows.rs:265:17
  26: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5
  27: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1973:9
  28: egui::containers::panel::SidePanel::show_inside_dyn::{{closure}}
             at ./crates/egui/src/containers/panel.rs:285:13
  29: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5
  30: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1973:9
  31: egui::containers::frame::Frame::show_dyn
             at ./crates/egui/src/containers/frame.rs:224:19
  32: egui::containers::frame::Frame::show
             at ./crates/egui/src/containers/frame.rs:215:9
  33: egui::containers::panel::SidePanel::show_inside_dyn
             at ./crates/egui/src/containers/panel.rs:282:30
  34: egui::containers::panel::SidePanel::show_dyn
             at ./crates/egui/src/containers/panel.rs:349:30
  35: egui::containers::panel::SidePanel::show
             at ./crates/egui/src/containers/panel.rs:334:9
  36: egui_demo_lib::demo::demo_app_windows::DemoWindows::desktop_ui
             at ./crates/egui_demo_lib/src/demo/demo_app_windows.rs:243:9
  37: egui_demo_lib::demo::demo_app_windows::DemoWindows::ui
             at ./crates/egui_demo_lib/src/demo/demo_app_windows.rs:177:13
  38: <egui_demo_app::wrap_app::DemoApp as eframe::epi::App>::update
             at ./crates/egui_demo_app/src/wrap_app.rs:31:9
  39: egui_demo_app::wrap_app::WrapApp::show_selected_app
             at ./crates/egui_demo_app/src/wrap_app.rs:370:17
  40: <egui_demo_app::wrap_app::WrapApp as eframe::epi::App>::update
             at ./crates/egui_demo_app/src/wrap_app.rs:279:9
  41: eframe::native::epi_integration::EpiIntegration::update::{{closure}}
             at ./crates/eframe/src/native/epi_integration.rs:517:17
  42: egui::context::Context::run
             at ./crates/egui/src/context.rs:515:9
  43: eframe::native::epi_integration::EpiIntegration::update
             at ./crates/eframe/src/native/epi_integration.rs:509:27
  44: eframe::native::run::glow_integration::GlowWinitRunning::run_ui_and_paint
             at ./crates/eframe/src/native/run.rs:545:17
  45: <eframe::native::run::glow_integration::GlowWinitApp as eframe::native::run::WinitApp>::run_ui_and_paint
             at ./crates/eframe/src/native/run.rs:1700:17
  46: eframe::native::run::run_and_return::{{closure}}
             at ./crates/eframe/src/native/run.rs:184:17
  47: winit::platform_impl::platform::sticky_exit_callback
             at /home/ygor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.6/src/platform_impl/linux/mod.rs:884:9
  48: winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::run_return
             at /home/ygor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.6/src/platform_impl/linux/wayland/event_loop/mod.rs:549:21
  49: winit::platform_impl::platform::EventLoop<T>::run_return
             at /home/ygor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.6/src/platform_impl/linux/mod.rs:785:56
  50: <winit::event_loop::EventLoop<T> as winit::platform::run_return::EventLoopExtRunReturn>::run_return
             at /home/ygor/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.6/src/platform/run_return.rs:51:9
  51: eframe::native::run::run_and_return
             at ./crates/eframe/src/native/run.rs:169:5
  52: eframe::native::run::glow_integration::run_glow::{{closure}}
             at ./crates/eframe/src/native/run.rs:1796:17
  53: eframe::native::run::with_event_loop::{{closure}}
             at ./crates/eframe/src/native/run.rs:151:9
  54: std::thread::local::LocalKey<T>::try_with
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/thread/local.rs:252:16
  55: std::thread::local::LocalKey<T>::with
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/thread/local.rs:228:9
  56: eframe::native::run::with_event_loop
             at ./crates/eframe/src/native/run.rs:145:5
  57: eframe::native::run::glow_integration::run_glow
             at ./crates/eframe/src/native/run.rs:1793:20
  58: eframe::run_native
             at ./crates/eframe/src/lib.rs:227:13
  59: egui_demo_app::main
             at ./crates/egui_demo_app/src/main.rs:30:5
  60: core::ops::function::FnOnce::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5

```
</Details>

**Comment by emilk** [comment]
Thanks for the report!
