### ISSUE TITLE
egui_demo_app crashes: GlutinCreationError(CreationErrors([NoAvailablePixelFormat, OsError("Couldn\'t setup vsync: expected interval `1` but got `0`")]))

### ISSUE THREAD

**Issue by alopatindev** [emilk/egui#384]
```
$ RUST_BACKTRACE=1 cargo run --release -p egui_demo_app
    Finished release [optimized] target(s) in 0.07s
     Running `target/release/egui_demo_app`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: GlutinCreationError(CreationErrors([NoAvailablePixelFormat, OsError("Couldn\'t setup vsync: expected interval `1` but got `0`")]))', egui_glium/src/backend.rs:112:85
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/option.rs:1329:5
   3: egui_glium::backend::run
   4: eframe::run_native
   5: egui_demo_app::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
$ RUST_BACKTRACE=full cargo run --release -p egui_demo_app
    Finished release [optimized] target(s) in 0.07s
     Running `target/release/egui_demo_app`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: GlutinCreationError(CreationErrors([NoAvailablePixelFormat, OsError("Couldn\'t setup vsync: expected interval `1` but got `0`")]))', egui_glium/src/backend.rs:112:85
stack backtrace:
   0:     0x55664b2a6440 - std::backtrace_rs::backtrace::libunwind::trace::h63b7a90188ab5fb3
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55664b2a6440 - std::backtrace_rs::backtrace::trace_unsynchronized::h80aefbf9b851eca7
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55664b2a6440 - std::sys_common::backtrace::_print_fmt::hbef05ae4237a4d72
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55664b2a6440 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h28abce2fdb9884c2
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55664b2c905f - core::fmt::write::h3b84512577ca38a8
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/fmt/mod.rs:1092:17
   5:     0x55664b2a37c2 - std::io::Write::write_fmt::h465f8feea02e2aa1
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/io/mod.rs:1572:15
   6:     0x55664b2a85c5 - std::sys_common::backtrace::_print::h525280ee0d29bdde
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55664b2a85c5 - std::sys_common::backtrace::print::h1f0f5b9f3ef8fb78
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55664b2a85c5 - std::panicking::default_hook::{{closure}}::ha5838f6faa4a5a8f
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:208:50
   9:     0x55664b2a8073 - std::panicking::default_hook::hfb9fe98acb0dcb3b
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:225:9
  10:     0x55664b2a8bcd - std::panicking::rust_panic_with_hook::hb89f5f19036e6af8
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:591:17
  11:     0x55664b2a8767 - std::panicking::begin_panic_handler::{{closure}}::h119e7951427f41da
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:497:13
  12:     0x55664b2a68fc - std::sys_common::backtrace::__rust_end_short_backtrace::hce386c44bf47a128
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55664b2a86c9 - rust_begin_unwind
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
  14:     0x55664af81f71 - core::panicking::panic_fmt::h2242888e8769cd33
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:92:14
  15:     0x55664af81e63 - core::option::expect_none_failed::hb1edf11f73e63728
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/option.rs:1329:5
  16:     0x55664af926db - egui_glium::backend::run::h8b2df314b6661eed
  17:     0x55664af83824 - eframe::run_native::h10a96bd42904d401
  18:     0x55664af8335d - egui_demo_app::main::h0856fbf29e9dd66c
  19:     0x55664af82723 - std::sys_common::backtrace::__rust_begin_short_backtrace::hdc236e54a2e2634c
  20:     0x55664af83709 - std::rt::lang_start::{{closure}}::h2f02176c3f541878
  21:     0x55664b2a8fca - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h44574effd2120c86
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/ops/function.rs:259:13
  22:     0x55664b2a8fca - std::panicking::try::do_call::h10b0bd4879c8dfb0
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:379:40
  23:     0x55664b2a8fca - std::panicking::try::h60c6780d33419e92
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:343:19
  24:     0x55664b2a8fca - std::panic::catch_unwind::h111f33e08c52e2ce
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panic.rs:431:14
  25:     0x55664b2a8fca - std::rt::lang_start_internal::h126f2e09345dbfda
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/rt.rs:51:25
  26:     0x55664af83402 - main
  27:     0x7fecb0842ebb - __libc_start_main
  28:     0x55664af8265a - _start
  29:                0x0 - <unknown>
```

OS: Gentoo GNU/Linux

x11-base/xorg-server-1.20.11
x11-drivers/xf86-video-intel-2.99.917_p20201215 (USE="dri sna udev -debug -tools -uxa -xvmc")
media-libs/mesa-20.3.5
sys-kernel/vanilla-sources-5.9.14

Hardware: Lenovo ideapad Y700-17ISK with Intel Corporation HD Graphics 530

glutin examples run without this error

`/etc/X11/xorg.conf`:
```
Section "Files"
    FontPath        "/usr/share/fonts/100dpi"
    FontPath        "/usr/share/fonts/75dpi"
    FontPath        "/usr/share/fonts/cyrillic"
    FontPath        "/usr/share/fonts/intlfonts"
    FontPath	    "/usr/share/fonts/misc"
    FontPath        "/usr/share/fonts/terminus"
EndSection

Section "ServerFlags"
    Option "BlankTime" "0"
    Option "StandbyTime" "0"
    Option "SuspendTime" "0"
    Option "OffTime" "600"
EndSection

Section "Monitor"
    Identifier "Monitor0"
    ModeLine "1920x1080_119.94"  369.25  1920 2080 2288 2656  1080 1083 1088 1160 -hsync +vsync
    Option "PreferredMode" "3440x1440"
EndSection

Section "Screen"
    Identifier "Screen0"
    Monitor "Monitor0"
    SubSection     "Display"
        Depth       24
        Modes      "3440x1440"
    EndSubSection
EndSection

Section "Device"
    Identifier "Intel Graphics"
    Driver "intel"
    Option "DRI" "3"
    Option "AccelMethod" "sna"
    Option "TearFree" "true"
EndSection

Section "InputClass"
    Identifier "system-keyboard"
    MatchIsKeyboard "on"
    Option "XkbLayout" "us,ru"
    Option "XkbOptions" "grp:caps_toggle,lv3:rwin_switch,compose:ralt,grp_led:caps,compose:rwin"
EndSection
```

**Comment by alopatindev** [comment]
This reproduces only with the following `~/.drirc`:
```
<driconf>
    <device screen="0" driver="dri2">
        <application name="Default">
            <option name="vblank_mode" value="0"/>
        </application>
    </device>
</driconf>
```

**Comment by emilk** [comment]
Interesting! Does it still crash if you remove the `transparent: true` in `egui_demo_app/src/main.rs`?

**Comment by alopatindev** [comment]
> Does it still crash if you remove the transparent: true in egui_demo_app/src/main.rs?

Yes, the same stacktrace and error

**Comment by alopatindev** [comment]
Here's stacktrace from debug build
```
     Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running `target/debug/egui_demo_app`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: GlutinCreationError(CreationErrors([NoAvailablePixelFormat, OsError("Couldn\'t setup vsync: expected interval `1` but got `0`")]))', egui_glium/src/backend.rs:112:85
stack backtrace:
   0:     0x555a29532290 - std::backtrace_rs::backtrace::libunwind::trace::h63b7a90188ab5fb3
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x555a29532290 - std::backtrace_rs::backtrace::trace_unsynchronized::h80aefbf9b851eca7
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x555a29532290 - std::sys_common::backtrace::_print_fmt::hbef05ae4237a4d72
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x555a29532290 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h28abce2fdb9884c2
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x555a29554edf - core::fmt::write::h3b84512577ca38a8
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/fmt/mod.rs:1092:17
   5:     0x555a2952f612 - std::io::Write::write_fmt::h465f8feea02e2aa1
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/io/mod.rs:1572:15
   6:     0x555a29534415 - std::sys_common::backtrace::_print::h525280ee0d29bdde
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x555a29534415 - std::sys_common::backtrace::print::h1f0f5b9f3ef8fb78
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x555a29534415 - std::panicking::default_hook::{{closure}}::ha5838f6faa4a5a8f
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:208:50
   9:     0x555a29533ec3 - std::panicking::default_hook::hfb9fe98acb0dcb3b
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:225:9
  10:     0x555a29534a1d - std::panicking::rust_panic_with_hook::hb89f5f19036e6af8
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:591:17
  11:     0x555a295345b7 - std::panicking::begin_panic_handler::{{closure}}::h119e7951427f41da
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:497:13
  12:     0x555a2953274c - std::sys_common::backtrace::__rust_end_short_backtrace::hce386c44bf47a128
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x555a29534519 - rust_begin_unwind
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
  14:     0x555a289e7521 - core::panicking::panic_fmt::h2242888e8769cd33
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:92:14
  15:     0x555a289e7413 - core::option::expect_none_failed::hb1edf11f73e63728
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/option.rs:1329:5
  16:     0x555a28a867b3 - core::result::Result<T,E>::unwrap::h373c92373b6eeed2
                               at /home/al/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:1037:23
  17:     0x555a28a01af3 - egui_glium::backend::create_display::h4970088a6c8c18e7
                               at /home/al/git-extra/egui/egui_glium/src/backend.rs:112:19
  18:     0x555a28a0272c - egui_glium::backend::run::hdf853e7ebf2cfb0d
                               at /home/al/git-extra/egui/egui_glium/src/backend.rs:177:19
  19:     0x555a289e8941 - eframe::run_native::h087ce8185a9900f9
                               at /home/al/git-extra/egui/eframe/src/lib.rs:66:5
  20:     0x555a289e81b7 - egui_demo_app::main::hb775074d50ae7030
                               at /home/al/git-extra/egui/egui_demo_app/src/main.rs:18:5
  21:     0x555a289e7d4b - core::ops::function::FnOnce::call_once::h5d47f8e3bf0fc460
                               at /home/al/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  22:     0x555a289e7dbe - std::sys_common::backtrace::__rust_begin_short_backtrace::h4156d48a806241cc
                               at /home/al/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:125:18
  23:     0x555a289e88a1 - std::rt::lang_start::{{closure}}::h77b374a24a3b12b1
                               at /home/al/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:66:18
  24:     0x555a29534e1a - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h44574effd2120c86
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/ops/function.rs:259:13
  25:     0x555a29534e1a - std::panicking::try::do_call::h10b0bd4879c8dfb0
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:379:40
  26:     0x555a29534e1a - std::panicking::try::h60c6780d33419e92
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:343:19
  27:     0x555a29534e1a - std::panic::catch_unwind::h111f33e08c52e2ce
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panic.rs:431:14
  28:     0x555a29534e1a - std::rt::lang_start_internal::h126f2e09345dbfda
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/rt.rs:51:25
  29:     0x555a289e8880 - std::rt::lang_start::h2598fe8184e2e1f9
                               at /home/al/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:65:5
  30:     0x555a289e824c - main
  31:     0x7fcf6713cebb - __libc_start_main
  32:     0x555a289e7c2a - _start
  33:                0x0 - <unknown>
```

**Comment by emilk** [comment]
Does the `glium` example work? https://github.com/glium/glium

**Comment by alopatindev** [comment]
Nope, the same error
```
$ RUST_BACKTRACE=full cargo lrun --example blitting
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/examples/blitting`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: GlutinCreationError(CreationErrors([NoAvailablePixelFormat, OsError("Couldn\'t setup vsync: expected interval `1` but got `0`")]))', examples/blitting.rs:15:60
stack backtrace:
   0:     0x5555b3fd6d20 - std::backtrace_rs::backtrace::libunwind::trace::h63b7a90188ab5fb3
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x5555b3fd6d20 - std::backtrace_rs::backtrace::trace_unsynchronized::h80aefbf9b851eca7
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5555b3fd6d20 - std::sys_common::backtrace::_print_fmt::hbef05ae4237a4d72
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x5555b3fd6d20 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h28abce2fdb9884c2
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x5555b3ff612f - core::fmt::write::h3b84512577ca38a8
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/fmt/mod.rs:1092:17
   5:     0x5555b3fd3d02 - std::io::Write::write_fmt::h465f8feea02e2aa1
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/io/mod.rs:1572:15
   6:     0x5555b3fd8e65 - std::sys_common::backtrace::_print::h525280ee0d29bdde
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x5555b3fd8e65 - std::sys_common::backtrace::print::h1f0f5b9f3ef8fb78
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x5555b3fd8e65 - std::panicking::default_hook::{{closure}}::ha5838f6faa4a5a8f
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:208:50
   9:     0x5555b3fd8913 - std::panicking::default_hook::hfb9fe98acb0dcb3b
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:225:9
  10:     0x5555b3fd946d - std::panicking::rust_panic_with_hook::hb89f5f19036e6af8
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:591:17
  11:     0x5555b3fd9007 - std::panicking::begin_panic_handler::{{closure}}::h119e7951427f41da
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:497:13
  12:     0x5555b3fd71dc - std::sys_common::backtrace::__rust_end_short_backtrace::hce386c44bf47a128
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x5555b3fd8f69 - rust_begin_unwind
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
  14:     0x5555b363a841 - core::panicking::panic_fmt::h2242888e8769cd33
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:92:14
  15:     0x5555b363a733 - core::option::expect_none_failed::hb1edf11f73e63728
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/option.rs:1329:5
  16:     0x5555b36cb313 - core::result::Result<T,E>::unwrap::h369448299f88ea48
                               at /home/al/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:1037:23
  17:     0x5555b36fca17 - blitting::main::h8425da0365d8be19
                               at /home/al/git-extra/glium/examples/blitting.rs:15:19
  18:     0x5555b36ac06b - core::ops::function::FnOnce::call_once::hf4697dcfa2bcc0f4
                               at /home/al/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  19:     0x5555b36c6f3e - std::sys_common::backtrace::__rust_begin_short_backtrace::h492465746eedbc02
                               at /home/al/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:125:18
  20:     0x5555b36a3341 - std::rt::lang_start::{{closure}}::h874773e449aac8f8
                               at /home/al/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:66:18
  21:     0x5555b3fd996a - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h44574effd2120c86
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/ops/function.rs:259:13
  22:     0x5555b3fd996a - std::panicking::try::do_call::h10b0bd4879c8dfb0
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:379:40
  23:     0x5555b3fd996a - std::panicking::try::h60c6780d33419e92
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:343:19
  24:     0x5555b3fd996a - std::panic::catch_unwind::h111f33e08c52e2ce
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panic.rs:431:14
  25:     0x5555b3fd996a - std::rt::lang_start_internal::h126f2e09345dbfda
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/rt.rs:51:25
  26:     0x5555b36a3320 - std::rt::lang_start::ha243bde1b8fcf4a1
                               at /home/al/.rustup/toolchains/1.52.1-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:65:5
  27:     0x5555b36fd5bc - main
  28:     0x7fbedf0cfebb - __libc_start_main
  29:     0x5555b363af4a - _start
  30:                0x0 - <unknown>
```

**Comment by emilk** [comment]
Then I suggest you file an issue in the `glium` repository

**Comment by emilk** [comment]
Closed in favor of https://github.com/glium/glium/issues/1929
