### ISSUE TITLE
thread 'main' panicked at 'assertion failed: child_size.x >= 0.0 && child_size.y >= 0.0'

### ISSUE THREAD

**Issue by OvermindDL1** [emilk/egui#395]
**Describe the bug**

Stacktrace from a Windows user who compiled it themselves and ran it, then upon minimizing it:
```
thread 'main' panicked at 'assertion failed: child_size.x >= 0.0 && child_size.y >= 0.0', C:\Users\Tom\.cargo\registry\src\github.com-1ecc6299db9ec823\egui-0.11.0\src\layout.rs:535:9
--
  | stack backtrace:
  | 0: std::panicking::begin_panic_handler
  | at /rustc/ca82264ec7556a6011b9d3f1b2fd4c7cd0bc8ae2\/library\std\src\panicking.rs:493
  | 1: core::panicking::panic_fmt
  | at /rustc/ca82264ec7556a6011b9d3f1b2fd4c7cd0bc8ae2\/library\core\src\panicking.rs:92
  | 2: core::panicking::panic
  | at /rustc/ca82264ec7556a6011b9d3f1b2fd4c7cd0bc8ae2\/library\core\src\panicking.rs:50
  | 3: egui::layout::Layout::next_frame_ignore_wrap
  | at C:\Users\Tom\.cargo\registry\src\github.com-1ecc6299db9ec823\egui-0.11.0\src\layout.rs:535
  | 4: egui::layout::Layout::next_widget_space_ignore_wrap_justify
  | at C:\Users\Tom\.cargo\registry\src\github.com-1ecc6299db9ec823\egui-0.11.0\src\layout.rs:590
  | 5: egui::placer::Placer::next_widget_space_ignore_wrap_justify
  | at C:\Users\Tom\.cargo\registry\src\github.com-1ecc6299db9ec823\egui-0.11.0\src\placer.rs:199
  | 6: egui::placer::Placer::set_min_width
  | at C:\Users\Tom\.cargo\registry\src\github.com-1ecc6299db9ec823\egui-0.11.0\src\placer.rs:226
  | 7: egui::ui::Ui::set_min_width
  | at C:\Users\Tom\.cargo\registry\src\github.com-1ecc6299db9ec823\egui-0.11.0\src\ui.rs:355
  | 8: egui::containers::panel::{{impl}}::show::{{closure}}<tuple<>,closure-0>
  | at C:\Users\Tom\.cargo\registry\src\github.com-1ecc6299db9ec823\egui-0.11.0\src\containers\panel.rs:117
  | 9: egui::containers::frame::Frame::show<tuple<>,closure-1>
  | at C:\Users\Tom\.cargo\registry\src\github.com-1ecc6299db9ec823\egui-0.11.0\src\containers\frame.rs:139
  | 10: egui::containers::panel::TopPanel::show<tuple<>,closure-0>
  | at C:\Users\Tom\.cargo\registry\src\github.com-1ecc6299db9ec823\egui-0.11.0\src\containers\panel.rs:116
  | 11: mechaenetia::client_wgpu::states::main_menu::MainMenuState::render
  | at .\src\client_wgpu\states\main_menu.rs:196
  | 12: mechaenetia::client_wgpu::states::main_menu::on_update
  | at .\src\client_wgpu\states\main_menu.rs:374
  | 13: core::ops::function::Fn::call<fn(bevy_ecs::system::system_param::ResMut<bevy_egui::EguiContext>, bevy_ecs::system::system_param::ResMut<core::option::Option<mechaenetia::client_wgpu::states::main_menu::MainMenuState>>, bevy_ecs::system::system_param::ResM
  | at /rustc/ca82264ec7556a6011b9d3f1b2fd4c7cd0bc8ae2\library\core\src\ops\function.rs:70
  | 14: core::ops::function::impls::{{impl}}::call_mut<tuple<bevy_ecs::system::system_param::ResMut<bevy_egui::EguiContext>, bevy_ecs::system::system_param::ResMut<core::option::Option<mechaenetia::client_wgpu::states::main_menu::MainMenuState>>, bevy_ecs::system
  | at /rustc/ca82264ec7556a6011b9d3f1b2fd4c7cd0bc8ae2\library\core\src\ops\function.rs:248
  | 15: bevy_ecs::system::into_system::{{impl}}::run<tuple<>,fn(bevy_ecs::system::system_param::ResMut<bevy_egui::EguiContext>, bevy_ecs::system::system_param::ResMut<core::option::Option<mechaenetia::client_wgpu::states::main_menu::MainMenuState>>, bevy_ecs::sys
  | at C:\Users\Tom\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_ecs-0.5.0\src\system\into_system.rs:207
  | 16: bevy_ecs::system::into_system::{{impl}}::run_unsafe<tuple<>,tuple<>,tuple<bevy_ecs::system::system_param::ResMut<bevy_egui::EguiContext>, bevy_ecs::system::system_param::ResMut<core::option::Option<mechaenetia::client_wgpu::states::main_menu::MainMenuStat
  | at C:\Users\Tom\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_ecs-0.5.0\src\system\into_system.rs:147
  | 17: bevy_ecs::schedule::executor_parallel::{{impl}}::prepare_systems::{{closure}}
  | at C:\Users\Tom\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_ecs-0.5.0\src\schedule\executor_parallel.rs:200
  | 18: core::future::from_generator::{{impl}}::poll<generator-0>
  | at /rustc/ca82264ec7556a6011b9d3f1b2fd4c7cd0bc8ae2\library\core\src\future\mod.rs:80
  | 19: async_executor::{{impl}}::spawn::{{closure}}<tuple<>,core::future::from_generator::GenFuture<generator-0>>
  | at C:\Users\Tom\.cargo\registry\src\github.com-1ecc6299db9ec823\async-executor-1.4.0\src\lib.rs:138
  | 20: core::future::from_generator::{{impl}}::poll<generator-0>
  | at /rustc/ca82264ec7556a6011b9d3f1b2fd4c7cd0bc8ae2\library\core\src\future\mod.rs:80
  | 21: async_task::raw::RawTask<core::future::from_generator::GenFuture<generator-0>, tuple<>, closure-0>::run<core::future::from_generator::GenFuture<generator-0>,tuple<>,closure-0>
  | at C:\Users\Tom\.cargo\registry\src\github.com-1ecc6299db9ec823\async-task-4.0.3\src\raw.rs:489
  | 22: async_task::runnable::Runnable::run
  | at C:\Users\Tom\.cargo\registry\src\github.com-1ecc6299db9ec823\async-task-4.0.3\src\runnable.rs:309
  | 23: async_executor::Executor::try_tick
  | at C:\Users\Tom\.cargo\registry\src\github.com-1ecc6299db9ec823\async-executor-1.4.0\src\lib.rs:175
  | 24: bevy_tasks::task_pool::{{impl}}::scope::{{closure}}<closure-1,tuple<>>
  | at C:\Users\Tom\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_tasks-0.5.0\src\task_pool.rs:222
  | 25: std::thread::local::LocalKey<async_executor::LocalExecutor>::try_with<async_executor::LocalExecutor,closure-0,alloc::vec::Vec<tuple<>, alloc::alloc::Global>>
  | at /rustc/ca82264ec7556a6011b9d3f1b2fd4c7cd0bc8ae2\library\std\src\thread\local.rs:376
  | 26: std::thread::local::LocalKey<async_executor::LocalExecutor>::with<async_executor::LocalExecutor,closure-0,alloc::vec::Vec<tuple<>, alloc::alloc::Global>>
  | at /rustc/ca82264ec7556a6011b9d3f1b2fd4c7cd0bc8ae2\library\std\src\thread\local.rs:352
  | 27: bevy_tasks::task_pool::TaskPool::scope<closure-1,tuple<>>
  | at C:\Users\Tom\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_tasks-0.5.0\src\task_pool.rs:227
  | 28: bevy_ecs::schedule::executor_parallel::{{impl}}::run_systems
  | at C:\Users\Tom\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_ecs-0.5.0\src\schedule\executor_parallel.rs:121
  | 29: bevy_ecs::schedule::stage::{{impl}}::run
  | at C:\Users\Tom\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_ecs-0.5.0\src\schedule\stage.rs:825
  | 30: bevy_ecs::schedule::Schedule::run_once
  | at C:\Users\Tom\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_ecs-0.5.0\src\schedule\mod.rs:201
  | 31: bevy_ecs::schedule::{{impl}}::run
  | at C:\Users\Tom\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_ecs-0.5.0\src\schedule\mod.rs:220
  | 32: bevy_app::app::App::update
  | at C:\Users\Tom\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_app-0.5.0\src\app.rs:59
  | 33: bevy_winit::winit_runner_with::{{closure}}
  | at C:\Users\Tom\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_winit-0.5.0\src\lib.rs:485
  | 34: winit::platform_impl::platform::event_loop::{{impl}}::run_return::{{closure}}<tuple<>,closure-1>
  | at C:\Users\Tom\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\platform_impl\windows\event_loop.rs:204
  | 35: alloc::boxed::{{impl}}::call_mut<tuple<winit::event::Event<tuple<>>, mut winit::event_loop::ControlFlow*>,FnMut<tuple<winit::event::Event<tuple<>>, mut winit::event_loop::ControlFlow*>>,alloc::alloc::Global>
  | at /rustc/ca82264ec7556a6011b9d3f1b2fd4c7cd0bc8ae2\library\alloc\src\boxed.rs:1583
  | 36: winit::platform_impl::platform::event_loop::runner::{{impl}}::call_event_handler::{{closure}}<tuple<>>
  | at C:\Users\Tom\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\platform_impl\windows\event_loop\runner.rs:245
  | 37: std::panic::{{impl}}::call_once<tuple<>,closure-0>
  | at /rustc/ca82264ec7556a6011b9d3f1b2fd4c7cd0bc8ae2\library\std\src\panic.rs:345
  | 38: std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,tuple<>>
  | at /rustc/ca82264ec7556a6011b9d3f1b2fd4c7cd0bc8ae2\library\std\src\panicking.rs:381
  | 39: winit::platform_impl::platform::drop_handler::{{impl}}::drop
  | 40: std::panicking::try<tuple<>,std::panic::AssertUnwindSafe<closure-0>>
  | at /rustc/ca82264ec7556a6011b9d3f1b2fd4c7cd0bc8ae2\library\std\src\panicking.rs:343
  | 41: std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,tuple<>>
  | at /rustc/ca82264ec7556a6011b9d3f1b2fd4c7cd0bc8ae2\library\std\src\panic.rs:431
  | 42: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple<>>::catch_unwind<tuple<>,tuple<>,closure-0>
  | at C:\Users\Tom\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\platform_impl\windows\event_loop\runner.rs:152
  | 43: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple<>>::call_event_handler<tuple<>>
  | at C:\Users\Tom\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\platform_impl\windows\event_loop\runner.rs:253
  | 44: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple<>>::move_state_to<tuple<>>
  | at C:\Users\Tom\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\platform_impl\windows\event_loop\runner.rs:297
  | 45: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple<>>::main_events_cleared<tuple<>>
  | at C:\Users\Tom\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\platform_impl\windows\event_loop\runner.rs:228
  | 46: winit::platform_impl::platform::event_loop::flush_paint_messages<tuple<>>
  | at C:\Users\Tom\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\platform_impl\windows\event_loop.rs:676
  | 47: winit::platform_impl::platform::event_loop::thread_event_target_callback::{{closure}}<tuple<>>
  | at C:\Users\Tom\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\platform_impl\windows\event_loop.rs:1967
  | 48: std::panic::{{impl}}::call_once<isize,closure-0>
  | at /rustc/ca82264ec7556a6011b9d3f1b2fd4c7cd0bc8ae2\library\std\src\panic.rs:344
  | 49: std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure-0>,isize>
  | at /rustc/ca82264ec7556a6011b9d3f1b2fd4c7cd0bc8ae2\library\std\src\panicking.rs:379
  | 50: winit::platform_impl::platform::drop_handler::{{impl}}::drop
  | 51: std::panicking::try<isize,std::panic::AssertUnwindSafe<closure-0>>
  | at /rustc/ca82264ec7556a6011b9d3f1b2fd4c7cd0bc8ae2\library\std\src\panicking.rs:343
  | 52: std::panic::catch_unwind<std::panic::AssertUnwindSafe<closure-0>,isize>
  | at /rustc/ca82264ec7556a6011b9d3f1b2fd4c7cd0bc8ae2\library\std\src\panic.rs:432
  | 53: winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple<>>::catch_unwind<tuple<>,isize,closure-0>
  | at C:\Users\Tom\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\platform_impl\windows\event_loop\runner.rs:152
  | 54: winit::platform_impl::platform::event_loop::thread_event_target_callback<tuple<>>
  | at C:\Users\Tom\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\platform_impl\windows\event_loop.rs:2151
  | 55: DefSubclassProc
  | 56: DefSubclassProc
  | 57: GetWindowDC
  | 58: SetWindowTextW
  | 59: IsDialogMessageW
  | 60: KiUserCallbackDispatcher
  | 61: BeginPaint
  | 62: BeginPaint
  | 63: winit::platform_impl::platform::event_loop::EventLoop<tuple<>>::run_return<tuple<>,closure-1>
  | at C:\Users\Tom\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\platform_impl\windows\event_loop.rs:218
  | 64: winit::platform_impl::platform::event_loop::EventLoop<tuple<>>::run<tuple<>,closure-1>
  | at C:\Users\Tom\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\platform_impl\windows\event_loop.rs:188
  | 65: winit::event_loop::EventLoop<tuple<>>::run<tuple<>,closure-1>
  | at C:\Users\Tom\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\event_loop.rs:154
  | 66: bevy_winit::run<closure-1>
  | at C:\Users\Tom\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_winit-0.5.0\src\lib.rs:171
  | 67: bevy_winit::winit_runner_with
  | at C:\Users\Tom\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_winit-0.5.0\src\lib.rs:493
  | 68: bevy_winit::winit_runner
  | at C:\Users\Tom\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_winit-0.5.0\src\lib.rs:211
  | 69: core::ops::function::Fn::call<fn(bevy_app::app::App),tuple<bevy_app::app::App>>
  | at /rustc/ca82264ec7556a6011b9d3f1b2fd4c7cd0bc8ae2\library\core\src\ops\function.rs:70
  | 70: alloc::boxed::{{impl}}::call<tuple<bevy_app::app::App>,Fn<tuple<bevy_app::app::App>>,alloc::alloc::Global>
  | at /rustc/ca82264ec7556a6011b9d3f1b2fd4c7cd0bc8ae2\library\alloc\src\boxed.rs:1590
  | 71: bevy_app::app::App::run
  | at C:\Users\Tom\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_app-0.5.0\src\app.rs:68
  | 72: bevy_app::app_builder::AppBuilder::run
  | at C:\Users\Tom\.cargo\registry\src\github.com-1ecc6299db9ec823\bevy_app-0.5.0\src\app_builder.rs:50
  | 73: mechaenetia::core::{{impl}}::run::{{closure}}
  | at .\src\core\mod.rs:86
  | 74: mechaenetia::core::Engine::custom_run<tuple<>,core::convert::Infallible,closure-0>
  | at .\src\core\mod.rs:145
  | 75: mechaenetia::core::Engine::run
  | at .\src\core\mod.rs:87
  | 76: mechaenetia::main
  | at .\src\main.rs:69
  | 77: core::ops::function::FnOnce::call_once<fn() -> core::result::Result<tuple<>, anyhow::Error>,tuple<>>
  | at /rustc/ca82264ec7556a6011b9d3f1b2fd4c7cd0bc8ae2\library\core\src\ops\function.rs:227
  | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

The commit on the project they used was:  https://github.com/Mechaenetia/mechaenetia/tree/fae54e4e812e37c47368000d258a485b71c6c27b

I am unable to replicate it on linux here and I do not have a windows system to test with, but the crux of the issue is that windows seems to be reporting a 0 sized window when it minimizes (and linux isn't), which is breaking something in egui (where I'm not personally setting any sizes in it whatsoever).

I would expect egui to return an error or something if such an issue happened, not panic, or rather in this case to just not render what's in the 0-sized container as that seems most reasonable.

**To Reproduce**
1. Be on windows 7.
2. Clone https://github.com/Mechaenetia/mechaenetia.git and checkout commit fae54e4e812e37c47368000d258a485b71c6c27b
3. Run the client with its default features so it has the wgpu based client and run with the wgpu client by passing in the argument `--client=wgpu`.
4. Minimize the client window.

**Expected behavior**

Not panic, it should just not render what's in a 0-sized container.

**Desktop (please complete the following information):**
 - OS: They stated Windows 7
 - Version:
```
[[package]]
name = "egui"
version = "0.11.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "2d7d6535c3ecdc8627a72c1c52d052d66cd9f71c238428690cc46bef9d1f2bce"
dependencies = [
 "epaint",
]
```

**Additional context**

The stacktrace report they sent me, copied above so not really necessary but if curious is at:  https://paste.gg/p/anonymous/aefe0b756c8646cbbd2bd687276ddc5c

The line of code they were executing was:  https://github.com/Mechaenetia/mechaenetia/blob/fae54e4e812e37c47368000d258a485b71c6c27b/src/client_wgpu/states/main_menu.rs#L192-L196

**Comment by OvermindDL1** [comment]
Specifically what it seems happened is that windows minimized the window, set its size to 0, which seems fine, but then when egui tried to layout the children elements with their margins and paddings and so forth then they shrunk to less then 0, thus triggering that assert.

**Comment by OvermindDL1** [comment]
The bevy_egui system apparently has a check to skip size changes of less than 1x1:
https://github.com/mvlabat/bevy_egui/blob/main/src/systems.rs#L81

So I'm guessing the padding and such is still causing the child layout to shrink below that?

**Comment by OfficialURL** [comment]
Bevy crashing upon minimizing seems to be a known issue that's come and went in different forms for quite some time. I get similar errors when minimizing my own Bevy application. For more info, this might be helpful: https://github.com/bevyengine/bevy/issues/899
