### ISSUE TITLE
possible regression in 0.28 vs 0.27 in dnd_drag_source

### ISSUE THREAD

**Issue by 3gx** [emilk/egui#4883]
**Describe the bug**

**To Reproduce**
1. In tutorial `https://github.com/emilk/egui/blob/master/crates/egui_demo_lib/src/demo/drag_and_drop.rs#L72C1-L75C1`,  
replace
```
                        let response = ui
                            .dnd_drag_source(item_id, item_location, |ui| {
                                ui.label(item);
                            })
                            .response;
```

with 

```
                        let response = ui
                            .dnd_drag_source(item_id, item_location, |ui| {
                                ui.vertical(|ui| {
                                  ui.label("--");
                                  ui.label(item);
                                 });
                            })
                            .response;
```

2. Click on it

3. Error 
```
thread 'main' panicked at /Users/egx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/egui-0.28.1/src/widget_rect.rs:142:17:
Widget changed layer_id during the frame
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at /Users/egx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/macos/app_state.rs:387:33:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }

```

**Expected behavior**
Can be dragged with 0.27

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 14.5

**Comment by HactarCE** [comment]
I'm experiencing this in my app, but I'm able to use `ui.push_id()` as a workaround. I can elaborate if anyone would like more details.

**Comment by 3gx** [comment]
> I'm experiencing this in my app, but I'm able to use `ui.push_id()` as a workaround. I can elaborate if anyone would like more details.

Yes, I would appreciate if you can share your workaround. Than you.

**Comment by HactarCE** [comment]
@3gx I'm using [my own version](https://github.com/HactarCE/Hyperspeedcube/blob/365866e5f57dce371bea7bd529b2a7a022d30518/hyperspeedcube/src/gui/components/dnd.rs#L99-L157) of egui's drag-and-drop API but the solution can probably be adapted to work. Try `ui.dnd_drag_source(|ui| ui.push_id(id, |ui| ...))` (with some unique `id`).

**Comment by emilk** [comment]
* Closed by https://github.com/emilk/egui/pull/5191
