### ISSUE TITLE
Crash on RHEL8

### ISSUE THREAD

**Issue by Blebowski** [emilk/egui#4926]
**Describe the bug**
Hi, when I run tests on RHEL8, I get crash

**To Reproduce**
1. cd examples
2. ./run_all.sh

**Log**:
```
(ts-python-env-yQ9mF3ZL-py3.8) [oille@runner4 examples]$ ./run_all.sh 
+ for example_name in *
+ '[' -d confirm_exit ']'
+ cargo run --quiet -p confirm_exit
thread 'main' panicked at /home/oille/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.2/src/platform_impl/linux/x11/mod.rs:240:14:
Error while checking for XInput2 query version reply: X11Error(X11Error { error_kind: Request, error_code: 1, sequence: 77, bad_value: 0, minor_opcode: 47, major_opcode: 130, extension_name: Some("XInputExtension"), request_name: Some("XIQueryVersion") })
stack backtrace:
   0:     0x55bac3d35226 - std::backtrace_rs::backtrace::libunwind::trace::hbee8a7973eeb6c93
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x55bac3d35226 - std::backtrace_rs::backtrace::trace_unsynchronized::hc8ac75eea3aa6899
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55bac3d35226 - std::sys_common::backtrace::_print_fmt::hc7f3e3b5298b1083
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x55bac3d35226 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hbb235daedd7c6190
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55bac3d632e0 - core::fmt::rt::Argument::fmt::h76c38a80d925a410
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/rt.rs:142:9
   5:     0x55bac3d632e0 - core::fmt::write::h3ed6aeaa977c8e45
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/fmt/mod.rs:1120:17
   6:     0x55bac3d3110f - std::io::Write::write_fmt::h78b18af5775fedb5
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/io/mod.rs:1810:15
   7:     0x55bac3d35004 - std::sys_common::backtrace::_print::h5d645a07e0fcfdbb
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x55bac3d35004 - std::sys_common::backtrace::print::h85035a511aafe7a8
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x55bac3d36757 - std::panicking::default_hook::{{closure}}::hcce8cea212785a25
  10:     0x55bac3d364b9 - std::panicking::default_hook::hf5fcb0f213fe709a
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:292:9
  11:     0x55bac3d36be8 - std::panicking::rust_panic_with_hook::h095fccf1dc9379ee
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:779:13
  12:     0x55bac3d36ac2 - std::panicking::begin_panic_handler::{{closure}}::h032ba12139b353db
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:657:13
  13:     0x55bac3d35726 - std::sys_common::backtrace::__rust_end_short_backtrace::h9259bc2ff8fd0f76
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:171:18
  14:     0x55bac3d36820 - rust_begin_unwind
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
  15:     0x55bac33d9835 - core::panicking::panic_fmt::h784f20a50eaab275
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
  16:     0x55bac33d9e73 - core::result::unwrap_failed::h03d8a5018196e1cd
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1649:5
  17:     0x55bac342078b - core::result::Result<T,E>::expect::h30512e3aae340fd1
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1030:23
  18:     0x55bac3513bbd - winit::platform_impl::platform::x11::EventLoop<T>::new::h0959a0ed3c22cae6
                               at /home/oille/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.2/src/platform_impl/linux/x11/mod.rs:235:9
  19:     0x55bac346ab9d - winit::platform_impl::platform::EventLoop<T>::new_x11_any_thread::h1da94aaa57c15c15
                               at /home/oille/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.2/src/platform_impl/linux/mod.rs:785:25
  20:     0x55bac346b19f - winit::platform_impl::platform::EventLoop<T>::new::h6b6fa27e18286ea0
                               at /home/oille/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.2/src/platform_impl/linux/mod.rs:769:27
  21:     0x55bac341f024 - winit::event_loop::EventLoopBuilder<T>::build::h99a9d8d2899a128c
                               at /home/oille/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.30.2/src/event_loop.rs:125:25
  22:     0x55bac343891d - eframe::native::run::create_event_loop::h29b73b5ed5cd2ef5
                               at /tmp/egui/crates/eframe/src/native/run.rs:28:8
  23:     0x55bac3419743 - eframe::native::run::with_event_loop::{{closure}}::h5f98f2b8421cdbbf
                               at /tmp/egui/crates/eframe/src/native/run.rs:49:36
  24:     0x55bac3487a59 - std::thread::local::LocalKey<T>::try_with::h49afd0b74a9d034d
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/thread/local.rs:270:16
  25:     0x55bac348734d - std::thread::local::LocalKey<T>::with::h844b93004433d71c
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/thread/local.rs:246:9
  26:     0x55bac3419530 - eframe::native::run::with_event_loop::h7e48a0a9035972b1
                               at /tmp/egui/crates/eframe/src/native/run.rs:41:5
  27:     0x55bac3438aee - eframe::native::run::run_glow::hafd6856af6948c53
                               at /tmp/egui/crates/eframe/src/native/run.rs:342:16
  28:     0x55bac341ca89 - eframe::run_native::h9098a1b4f624fbc1
                               at /tmp/egui/crates/eframe/src/lib.rs:262:13
  29:     0x55bac33dd11a - confirm_exit::main::h7bbc6acd7c2dbb91
                               at /tmp/egui/examples/confirm_exit/src/main.rs:12:5
  30:     0x55bac33dae12 - core::ops::function::FnOnce::call_once::h39ae0ec17a5f8300
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
  31:     0x55bac33e06e5 - std::sys_common::backtrace::__rust_begin_short_backtrace::h95344dd39e9dc750
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/sys_common/backtrace.rs:155:18
  32:     0x55bac33e1886 - std::rt::lang_start::{{closure}}::hc5132c3c80b6a031
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:166:18
  33:     0x55bac3d2afd1 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h37600b1e5eea4ecd
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:284:13
  34:     0x55bac3d2afd1 - std::panicking::try::do_call::hb4bda49fa13a0c2b
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  35:     0x55bac3d2afd1 - std::panicking::try::h8bbf75149211aaaa
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  36:     0x55bac3d2afd1 - std::panic::catch_unwind::h8c78ec68ebea34cb
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  37:     0x55bac3d2afd1 - std::rt::lang_start_internal::{{closure}}::hffdf44a19fd9e220
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:48
  38:     0x55bac3d2afd1 - std::panicking::try::do_call::hcb3194972c74716d
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:552:40
  39:     0x55bac3d2afd1 - std::panicking::try::hcdc6892c5f0dba4c
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:516:19
  40:     0x55bac3d2afd1 - std::panic::catch_unwind::h4910beb4573f4776
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panic.rs:142:14
  41:     0x55bac3d2afd1 - std::rt::lang_start_internal::h6939038e2873596b
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:148:20
  42:     0x55bac33e185a - std::rt::lang_start::h96f8b68cb8fff5f3
                               at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/rt.rs:165:17
  43:     0x55bac33dd30e - main
  44:     0x7fa06de51d85 - __libc_start_main
  45:     0x55bac33da17e - _start
  46:                0x0 - <unknown>
```

**Expected behavior**
Not crashing

**Desktop (please complete the following information):**
 - OS: ```Linux runner1.tropic.prod.hq.sldev.cz 4.18.0-513.11.1.el8_9.x86_64 #1 SMP Thu Dec 7 03:06:13 EST 2023 x86_64 x86_64 x86_64 GNU/Linux```
 - Browser: N/A, running on CLI server machine via SSH with `-Y`

**Comment by emilk** [comment]
I think this ticket belongs in the `winit` repository
