### ISSUE TITLE
missing `libxkbcommon-x11.so` with `cargo build` in Ubuntu VM

### ISSUE THREAD

**Issue by edrihan** [emilk/egui#4970]
The only thing that works is compiling to wasm using trunk serve. Every `egui` example does this.

```
ed@Xubuntu:~/custom_font_style$ cargo run
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.55s
     Running `target/debug/custom_font_style`
thread 'main' panicked at /home/ed/.cargo/registry/src/index.crates.io-6f17d22bba15001f/xkbcommon-dl-0.4.2/src/x11.rs:59:28:
Library libxkbcommon-x11.so could not be loaded.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
ed@Xubuntu:~/custom_font_style$ 
```

So, I ran with `RUST-BACKTRACE=1`, getting the following output:

```
RUST_BACKTRACE=1 cargo run
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.63s
     Running `target/debug/custom_font_style`
thread 'main' panicked at /home/ed/.cargo/registry/src/index.crates.io-6f17d22bba15001f/xkbcommon-dl-0.4.2/src/x11.rs:59:28:
Library libxkbcommon-x11.so could not be loaded.
stack backtrace:
   0: rust_begin_unwind
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/panicking.rs:72:14
   2: core::panicking::panic_display
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/panicking.rs:262:5
   3: core::option::expect_failed
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/option.rs:1995:5
   4: core::option::Option<T>::expect
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/option.rs:898:21
   5: xkbcommon_dl::x11::xkbcommon_x11_handle
             at /home/ed/.cargo/registry/src/index.crates.io-6f17d22bba15001f/xkbcommon-dl-0.4.2/src/x11.rs:59:5
   6: core::ops::function::FnOnce::call_once
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/ops/function.rs:250:5
   7: once_cell::sync::Lazy<T,F>::force::{{closure}}
             at /home/ed/.cargo/registry/src/index.crates.io-6f17d22bba15001f/once_cell-1.19.0/src/lib.rs:1310:28
   8: once_cell::sync::OnceCell<T>::get_or_init::{{closure}}
             at /home/ed/.cargo/registry/src/index.crates.io-6f17d22bba15001f/once_cell-1.19.0/src/lib.rs:1120:57
   9: once_cell::imp::OnceCell<T>::initialize::{{closure}}
             at /home/ed/.cargo/registry/src/index.crates.io-6f17d22bba15001f/once_cell-1.19.0/src/imp_std.rs:72:23
  10: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/ops/function.rs:294:13
  11: once_cell::imp::initialize_or_wait
             at /home/ed/.cargo/registry/src/index.crates.io-6f17d22bba15001f/once_cell-1.19.0/src/imp_std.rs:196:20
  12: once_cell::imp::OnceCell<T>::initialize
             at /home/ed/.cargo/registry/src/index.crates.io-6f17d22bba15001f/once_cell-1.19.0/src/imp_std.rs:68:9
  13: once_cell::sync::OnceCell<T>::get_or_try_init
             at /home/ed/.cargo/registry/src/index.crates.io-6f17d22bba15001f/once_cell-1.19.0/src/lib.rs:1161:13
  14: once_cell::sync::OnceCell<T>::get_or_init
             at /home/ed/.cargo/registry/src/index.crates.io-6f17d22bba15001f/once_cell-1.19.0/src/lib.rs:1120:19
  15: once_cell::sync::Lazy<T,F>::force
             at /home/ed/.cargo/registry/src/index.crates.io-6f17d22bba15001f/once_cell-1.19.0/src/lib.rs:1309:13
  16: <once_cell::sync::Lazy<T,F> as core::ops::deref::Deref>::deref
             at /home/ed/.cargo/registry/src/index.crates.io-6f17d22bba15001f/once_cell-1.19.0/src/lib.rs:1376:13
  17: winit::platform_impl::platform::common::xkb::Context::from_x11_xkb
             at /home/ed/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/linux/common/xkb/mod.rs:102:13
  18: winit::platform_impl::platform::x11::EventLoop<T>::new
             at /home/ed/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/linux/x11/mod.rs:293:13
  19: winit::platform_impl::platform::EventLoop<T>::new_x11_any_thread
             at /home/ed/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/linux/mod.rs:811:25
  20: winit::platform_impl::platform::EventLoop<T>::new
             at /home/ed/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/linux/mod.rs:795:27
  21: winit::event_loop::EventLoopBuilder<T>::build
             at /home/ed/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/event_loop.rs:128:25
  22: eframe::native::run::create_event_loop
             at /home/ed/.cargo/registry/src/index.crates.io-6f17d22bba15001f/eframe-0.28.1/src/native/run.rs:35:8
  23: eframe::native::run::with_event_loop::{{closure}}
             at /home/ed/.cargo/registry/src/index.crates.io-6f17d22bba15001f/eframe-0.28.1/src/native/run.rs:56:36
  24: std::thread::local::LocalKey<T>::try_with
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/thread/local.rs:283:12
  25: std::thread::local::LocalKey<T>::with
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/thread/local.rs:260:9
  26: eframe::native::run::with_event_loop
             at /home/ed/.cargo/registry/src/index.crates.io-6f17d22bba15001f/eframe-0.28.1/src/native/run.rs:48:5
  27: eframe::native::run::run_glow
             at /home/ed/.cargo/registry/src/index.crates.io-6f17d22bba15001f/eframe-0.28.1/src/native/run.rs:397:16
  28: eframe::run_native
             at /home/ed/.cargo/registry/src/index.crates.io-6f17d22bba15001f/eframe-0.28.1/src/lib.rs:262:13
  29: custom_font_style::main
             at ./src/main.rs:11:5
  30: core::ops::function::FnOnce::call_once
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

**Comment by joshuaPurushothaman** [comment]
Hi, I had this issue even after following the apt install list in the README under Demo. This was under WSL2, with the `x11` Cargo feature enabled (not Wayland -- not sure if one is recommended over the other for WSL2 development).

The solution for me was to also `apt install libxkbcommon-x11-0`; the original error was `Library libxkbcommon-x11.so could not be loaded`.
