### ISSUE TITLE
Crash during initialization when using cpal library on Windows

### ISSUE THREAD

**Issue by timnewsham** [emilk/egui#598]
I have an egui application that runs fine normally. I recently tried to add audio support using the cpal library. Separately the cpal library code runs fine, but the egui application is now crashing in Windows while egui is initializing with the following:

```
thread 'main' panicked at 'OleInitialize failed! Result was: `RPC_E_CHANGED_MODE`. Make sure other crates are not using multithreaded COM library on the same thread or disable drag and drop support.', C:\Users\tnewsham\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\window.rs:86:25
stack backtrace:
   0: std::panicking::begin_panic<str>
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\library\std\src\panicking.rs:541
   1: winit::platform_impl::platform::window::{{impl}}::new::{{closure}}<egui_glium::backend::RequestRepaintEvent>
             at C:\Users\tnewsham\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\window.rs:86
   2: enum$<core::result::Result<winit::platform_impl::platform::window::Window, winit::error::OsError>>::map<winit::platform_impl::platform::window::Window,winit::error::OsError,winit::platform_impl::platform::window::Window,closure-0>
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633\library\core\src\result.rs:504
   3: winit::platform_impl::platform::window::Window::new<egui_glium::backend::RequestRepaintEvent>
             at C:\Users\tnewsham\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\platform_impl\windows\window.rs:76
   4: winit::window::WindowBuilder::build<egui_glium::backend::RequestRepaintEvent>
             at C:\Users\tnewsham\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.25.0\src\window.rs:370
   5: enum$<glutin::platform_impl::platform_impl::Context>::new_windowed<egui_glium::backend::RequestRepaintEvent>
             at C:\Users\tnewsham\.cargo\registry\src\github.com-1ecc6299db9ec823\glutin-0.27.0\src\platform_impl\windows\mod.rs:53
   6: glutin::ContextBuilder<enum$<glutin::context::NotCurrent>>::build_windowed<enum$<glutin::context::NotCurrent>,egui_glium::backend::RequestRepaintEvent>
             at C:\Users\tnewsham\.cargo\registry\src\github.com-1ecc6299db9ec823\glutin-0.27.0\src\windowed.rs:341
   7: glium::backend::glutin::Display::new<enum$<glutin::context::NotCurrent>,egui_glium::backend::RequestRepaintEvent>
             at C:\Users\tnewsham\.cargo\registry\src\github.com-1ecc6299db9ec823\glium-0.30.1\src\backend\glutin\mod.rs:75
   8: egui_glium::backend::create_display
             at C:\Users\tnewsham\.cargo\registry\src\github.com-1ecc6299db9ec823\egui_glium-0.13.1\src\backend.rs:112
   9: egui_glium::backend::run
             at C:\Users\tnewsham\.cargo\registry\src\github.com-1ecc6299db9ec823\egui_glium-0.13.1\src\backend.rs:177
  10: eframe::run_native
```

**Comment by timnewsham** [comment]
The solution is to set `native_options.drag_and_drop_support = false;` in my code.
This is slightly non-obvious, perhaps some docs could point wayward souls in the right direction...

**Comment by emilk** [comment]
Maybe `drag_and_drop_support` should default to `false` on Windows, since this seems like a horrible thing to figure out (thanks for figuring it out!).
